### ISSUE TITLE
Idea:  Create x13 downloaders

### ISSUE THREAD

**Issue by eddelbuettel** [christophsax/seasonal#119]
Have a look at what I do [here for Rblpapi](https://github.com/Rblp/Rblpapi/blob/master/configure) which need libraries from Bloomberg.  

Could we not do the same for x13 from Census?

I presume you have discussed with CRAN about what they would or would not take in terms of binary payload in the package?

**Comment by christophsax** [comment]
Many thanks for the suggestion. I had some similar thoughts when I started with the package, but never really pursued them. I found the Fortran compilation a bit tricky, but I guess it should be possible to work around these difficulties. If the Fortran code has to be included in the R package, I also need to check with the Census, as their license is not very [clear](https://www.census.gov/srd/www/x13as/).

I never checked with CRAN about what they would allow in terms of binary code in the package. If they would allow to include or download from Census, we could even have a window version, which would be obviously very neat. Do you have an Idea to whom to speak at CRAN?

**Comment by eddelbuettel** [comment]
There are (at least) two possibilities:
1. Create x13 binaries for the three main platforms, store them "somewhere", then have seasonal download them at its installation; that is closer to the Rblpapi mode where we don't even have the third party _sources_ but object code. This what I had in mind.
2. Compile the x13 binary from source when seasonal is installed; it puts higher demand on the system (ie need for (Fortran) compiler).

I found Uwe Ligges and Kurt Hornik to be quite responsive to concrete proposals.

**Comment by christophsax** [comment]
Thanks! Will give it a try.

**Comment by eddelbuettel** [comment]
:+1:

Let me know if I can help.  I use to ship a Linux binary of x11 (or x12) back in the day with Quantian.  At some point we all need to have a real conversation with Brian Monsell about saner distribution....

**Comment by christophsax** [comment]
For Windows, downloading the binaries from the Census should work fine (if this will be allowed by CRAN). I never had any problem of running it on a Windows system.

I used to distribute my own OS-X binaries, but since they require some additional libraries (which may be part of the system or not, depending on the OS version) I found it easier to compile it afresh each time. However, at [gretl](http://gretl.sourceforge.net/mac-intel-quartz.html), they managed to include these libraries in an (outdated) standalone application, so this could be a blueprint.

Installing from source in Ubuntu is easy (e.g. [here](https://github.com/rstudio/shinyapps-package-dependencies/blob/master/packages/seasonal/install), for RStudio shinyapps), but I don't know how hard it will be to get it work on different linux systems. Definitely may need your help.

**Comment by eddelbuettel** [comment]
I am familiar with gretl; I have been looking after it for Debian for all these years.  I'd try standalone binaries.  I have found github to be fine for hosting.    Or maybe if you have good-enough build recipes we can use those?

**Comment by christophsax** [comment]
Hi Dirk, I made a first attempt in the `x13download` branch. Feel free to modify whatever is needed.

Using devtools, I can now install `seasonal` with auto install on Windows, OS-X and Ubuntu:
```
devtools::install_github('christophsax/seasonal', ref = "x13download")
```

Windows seems to work fine, downloading directly from Census.

OS-X is a bit a problem. In the current version, I am building it from source, which takes a long time and also needs a recent version of gfortran (e.g., 5.2). The gfortran version on CRAN (4.2.3) does not work for some reason. It would be probably nicer if we could download a binary version, but I haven't managed to include the necessary libraries in a proper OS-X package, as they did for the gretl binaries.

For Linux, I only tried with Ubuntu, so far. Both installing from source or binary downloading works fine. Installing from source works fine with the version of gfortran included in Ubuntu. Since it is faster, the current version downloads the binaries from the [seasonalbin](https://github.com/christophsax/seasonalbin) repo. We could have binaries for the main distributions, and install it from source for the others?

Let me know what you think.

**Comment by eddelbuettel** [comment]
Sweet.  
Quick questions before I glance at the code:
- Windows downloads a binary, yes/no?
- OS X: if you have build issues, why not (offline) build a binary and download that as needed?
- Ubuntu: Exactly. Let's prebuild for the few distros we have access to, and leave source as a fallback.
Seems like a good plan.  

As I recall, the resulting binary can work as basic cmdline tool with little to no depends. So we could even attempt a statically compiled binary for _all_ or most Linux distros. I can help you with Docker to build on something minimal like Ubuntu 12.04 or 14.04 -- and as a static build this would run everywhere.

Sounds like a plan?

**Comment by eddelbuettel** [comment]
Ok, quick suggestions:
1. No need to wrap a tarball around the binary.  You could just upload x13.gz
2. Why the name `x13ashtml`?  It is html, it is a binary.
3. `ldd` shows few depends, we can clearly build this as a binary in which case it would run everywhere.  The package 'seasonalbin' (or a different name) would download a binary for the platform it is on, and package `seasonal` would just call the path provided by `seasonalbin`.  TADA--we have automated x13 deployment.   We should write a short two-page paper about that trick for the R Journal.

```
/tmp$ ldd x13ashtml
        linux-vdso.so.1 =>  (0x00007ffe39370000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f1d4dd75000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d4da6d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d4d855000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d4d48b000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f1d4d24c000)
        /lib64/ld-linux-x86-64.so.2 (0x00005555d92d9000)
/tmp$ 
```

**Comment by christophsax** [comment]
Yes, sounds great, also with the article!

So the main task would be to build some platform independent binaries both for linux and OS-X (ideally). For OS-X, we also only have a few dependencies (these are causing the build issues, as most of them come with gfortran, and are not present on OS-X by default):

```
Christophs-MacBook-Pro:x13 christoph$ otool -L x13ashtml
x13ashtml:
	/usr/local/gfortran/lib/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/gfortran/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/gfortran/lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```

To your other points:
- Yes, Windows is binary
- For OS-X building issues, I struggle to pack it as a 'no depends' binary. If you can show me how you do it on Linux, perhaps I can do the same here.
- x13html: Just a name for the binaries. There are two versions of x13, a 'html' and a 'non-html' version. They differ in what kind of output files are produced. 'seasonal' currently supports both versions, but the 'html' version is slightly easier to parse and I would like to drop support for the 'non-html' version at some point. I started with the non-html version and some people are still using it. Adding auto deployment would make it easier to push them to the html version.

**Comment by eddelbuettel** [comment]
Oh, I see re html vs non-html -- I was unaware.

So I guess if we settle on a build recipe for `x13` (the html version) then we should be able to use that on the Linuxes as well as on OS X.

**Comment by eddelbuettel** [comment]
Good news!  I just built x13ashtml from source (and have two corrections [for your wiki page](https://github.com/christophsax/seasonal/wiki/Compiling-X-13ARIMA-SEATS-from-Source-for-Ubuntu) -- do you want me to edit there or open an issue or just tell or ...) and it already creates a static binary.

I think we are done.  I just used Debian stable and oldstable via Docker and invoked the `x13ashtml` binary with switch -h:

```bash
/tmp/x13$ docker run --rm -ti -v $(pwd):/mnt debian:oldstable /mnt/x13ashtml -h

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 19
 Execution began  Dec 29, 2015  19.07.09 

 ERROR: Program option -h not defined.  Valid program options are 
        -I, -O, -M, -D, -C, -P, -W, -S, -N, -V, -R, -Q.
/tmp/x13$ docker run --rm -ti -v $(pwd):/mnt debian:stable /mnt/x13ashtml -h

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 19
 Execution began  Dec 29, 2015  19.07.15 

 ERROR: Program option -h not defined.  Valid program options are 
        -I, -O, -M, -D, -C, -P, -W, -S, -N, -V, -R, -Q.
/tmp/x13$ 
```

Works like a charm.

**Comment by christophsax** [comment]
Cool! The docker command allows you to test the binaries on different platforms, right? Your built should run on most Linuxes now, without the need of libraries? Would it even run on OS-X or do we still have to take care about? BTW, they also have a Redhat binary on the Census Website, but it never worked on Ubuntu.

Feel free to edit the wiki, but your other options work as well.

**Comment by eddelbuettel** [comment]
(Docker provides the ability to run different environments; they call them containers. Lighter and easier than virtual machines.  It's nice for these things. It does not cross operating systems ie cannot run OS X binaries for me.  You can run Docker on OS X and Windows, though, where it adds a thin Linux layer.)

Re the wiki, the comments were
- no need to rename `Adf.f` and `ADJREG.f`; they already existed as lower-case files. I just `rm`-ed them.
- no need to rename the `makefile.g77`; I just invoked as `make -f makefile.g77`. Worked fine.

Now: how did you construct the binary you posted?  Same thing?  I am surprised I get a static binary and you do not...  In the tarfile you link to I see

```make
$(PROGRAM):     $(OBJS) $(LIBS)
        $(LINKER) -static -o $@ $(OBJS) $(LDMAP) $(LIBS) $(LDFLAGS)
```

**Comment by christophsax** [comment]
Ah, I see. I run the same script as for [OS-X](https://github.com/christophsax/seasonal/blob/x13download/configure) and was happy that it run through. However, for the OS-X built, I had to remove the static option, as I got an error otherwise:

```
sed 's/ \-static / /' makefile.g77 > makefile.gfortran
```
So without this line, we get a Linux build without dependencies, that's cool. You think that would also work on other linuxes? I will try building on OS-X without removing the `-static` option.

As for the lower case renaming, I still see them capitalized:
```
ubuntu@ip-172-30-0-178:~$  tar -zxvf x13ashtmlsrc_V1.1_B19.tar.gz 
aaamain.f
abend.f
acfar.f
acfdgn.f
acf.f
Acf.f
acfhdr.f
addadj.f
addaic.f
addate.f
addeas.f
addfix.f
addlom.f
addmat.f
addmul.f
addotl.f
addsef.f
addsub.f
addtd.f
addusr.f
adestr.f
adjreg.f
ADJREG.f
```

I got it from here:
```
https://www.census.gov/ts/x13as/unix/x13ashtmlsrc_V1.1_B19.tar.gz
```

**Comment by christophsax** [comment]
Without the removing the `-static` option, I get an error on OS-X:
```
trm.o yprmy.o yrly.o rvarma.o rvtdrg.o prtukp.o svtukp.o savtpk.o     -s
ld: warning: option -s is obsolete and being ignored
ld: library not found for -lcrt0.o
collect2: error: ld returned 1 exit status
make: *** [x13ashtml] Error 1
```

**Comment by eddelbuettel** [comment]
Christoph, more slowly to separate the discussions we mixed here.

First, static and OS X: I think OS X may be a missing a static library. Probably little we can do. As OS X controls the distribution pretty well, maybe good enough if we provide a dynamic binary for the current OS X version?  Can you cover that and build it?

Second, static and Linux:  Yes, that is the point: run on other distributions and/or variants. I think we have that covered. I will try on a CentOS box at work.

Third, lower/upper case. You seem to confirm exactly what I said. There are _already_ lowercase versions of the file, so no need to renamed; we can just remove (or probably even ignore).

**Comment by christophsax** [comment]
Ok, now I have seen the lower case versions as well. When I untar them on OS-X, the lower case versions disappear for some reason. That's why renaming there is necessary.

I try to find a solution for OS-X. The problem is that for the dynamic binary, we still need to have gfortran installed, which is not included by out of the box.

**Comment by eddelbuettel** [comment]
Oh, I see re the race condition on OS X. In that case the `mv` command is indeed needed and spot on.

We could try to depend on gfortran on OS X, in the 'tell users they have to have it' sense. If I am not mistaken I have to do that for some other packages like RcppArmadillo too as the LAPACK bindings won't work without it.  But I don't have an OS X box so I am a little out of my depth here.

**Comment by christophsax** [comment]
Can you have a quick look at the gretl package of X-12 [here](http://sourceforge.net/projects/gretl/files/x13as/x13as-x86_64-darwin10.dmg/download). Somehow, they managed to ship the missing libraries together with the binary in a proper OS-X application

<img width="699" alt="pastedgraphic-3" src="https://cloud.githubusercontent.com/assets/1390827/12051264/56f0ad5a-af01-11e5-92d2-5f2d8d84d737.png">

The problem is that I don't know how to tell the complier to use the libraries I want to ship with the binaries, rather than those that are installed on my system.

**Comment by eddelbuettel** [comment]
We should talk to them. I know Allin and Jake because I have maintained gretl in Debian practically since day one (and am like you an econometrician by training, but pst, don't tell anyone ;-).  Maybe we can even pool on this.  They need the same binaries on the same platforms.

**Comment by christophsax** [comment]
Wow, that worked well! Seems we are almost done. I still have to do some tests on Macs that have no gfortran installed.

```
Christophs-MacBook-Pro:bin christoph$ otool -L x13ashtml
x13ashtml:
	@executable_path/../lib/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	@executable_path/../lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../lib/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)

Christophs-MacBook-Pro:bin christoph$ ./x13ashtml

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 19
 Execution began  Dec 30, 2015  21.24.35 

 ERROR: Must specify either an input specification file name
        (-i infile or infile) or an input metafile name (-m metafile).

        See Section 2 of the X-13ARIMA-SEATS Reference Manual for more
        information on how to run X-13ARIMA-SEATS.
```

- I put both the binaries and the build script to [seasonalbin](https://github.com/christophsax/seasonalbin/tree/master/os-x).
- I will adjust the configure script tomorrow.
- One thought about the Windows version: Shall we also but the Census binary in our Github repository? If we rely on the Census Website, they may rename the file after an update, which will break our procedure.

**Comment by eddelbuettel** [comment]
Nice.  My idea with the x13org was to collect these binaries there. When you use a github repo _with a branch called gh-pages_ then it acts as something web-accessible.  I was planning on putting the Linux binary there.  We can put the OS X bundle there too, which will then be unpacked with a corresponding run of the `install_name_tool`.  Ditto for Windows.   I'll then build a little R package to use this -- and seasonal could just rely on this.  

In that way, x13org would gather all the parts and pieces related to x13 binaries for use by seasonal and others, including gretl if they choose to do so.

**Comment by christophsax** [comment]
Ok, sounds good. You can add the Linux binary there and I will do the same for OS-X when I see how it is done. 

I guess the install_name_tool fix can be done in the build script before packing it. It does not need to be done locally.

**Comment by eddelbuettel** [comment]
I am wondering about that. 

If the path is absolute, we need to know where R is placing it and we bascially need to do what you did for Linux: have a tarball, expand the program and its underlying dylib files and encode the location of the dylibs in the program binary. 

If it is relative then we wouldn't have to.  I think it is the former though.

**Comment by christophsax** [comment]
I think it is relative:

```
@executable_path/../lib/libgfortran.3.dylib
```

`@executable_path` is a placeholder for the directory with the the x13ashtml binary. Also, im my tests, it runs wherever I move the files. I will do some more tests on a fresh OS-X system.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by eddelbuettel** [comment]
Alright, some progress to report!

1. First off, a new repo [x13prebuilt](https://github.com/x13org/x13prebuilt) which currently contains the statically compiled linux binary (which I also tested, successfully, under an older CentOS).   This will need the OS X binary as a tar.gz with the dylibs.  It would be great if you could roll that up.  Might be best to discuss in a new issue ticket over there...

2. Second, a new package [x13binary](https://github.com/x13org/x13binary) with a minimal installer which so far supports Linux.  The action happens in [configure](https://github.com/x13org/x13binary/blob/master/configure) where we fetch the Linux binary and put it into `inst/bin/` so that the package installs.  _This works_ and you could depend on this [x13binary](https://github.com/x13org/x13binary) in your [seasonal](https://github.com/christophsax/seasonal) package and then rely on a _predictable and reliably computable_ path.  So with this deployment on Linux is now auto-magic!

3. Work remains for OS X (via an `install_name_tool` managed binary with dynamic libraries); users should then be free from having to do anything by hand. Should work as long OS X remains binary compatible with itself.   

4. Similarly, for Windows we also need a statically-linked binary. I think Census has that.

Below is a log of what happens on Linux.

```bash
edd@don:~/git$ R CMD INSTALL x13binary_0.0.1.tar.gz 
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘x13binary’ ...
*** downloaded Linux binary
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (x13binary)
edd@don:~/git$ ls -l /usr/local/lib/R/site-library/x13binary/bin/
total 4844
-rw-rw-r-- 1 edd adm     104 Dec 30 21:37 README
-rwxrwxr-x 1 edd adm 4955824 Dec 30 21:37 x13ashtml
edd@don:~/git$ 
```

Oh, dang, one thing I overlooked as the 64-vs-32 bit issue.  Will build a 32-bit one tomorrow too.

Anyway, time for a break and cold one now.

/cc @AllinCottrell who wouldn't be subscribed to this issue as it is in your repo...

**Comment by eddelbuettel** [comment]
Ok. I just updated the x13prebuilt repo with a 32-bit binary, added a directory layer with 32/ and 64/ and updated the script.  And now it works on my (32-bit) laptop:

```bash
edd@don:~/git$ R CMD INSTALL x13binary_0.0.1.tar.gz 
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘x13binary’ ...
*** downloaded Linux binary
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (x13binary)
edd@don:~/git$ ls -l /usr/local/lib/R/site-library/x13binary/bin/
total 4424
-rw-rw-r-- 1 edd adm     104 Dec 30 21:50 README
-rwxrwxr-x 1 edd adm 4525656 Dec 30 21:50 x13ashtml
edd@don:~/git$ /usr/local/lib/R/site-library/x13binary/bin/x13ashtml 

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 19
 Execution began  Dec 30, 2015  21.51.01 

 ERROR: Must specify either an input specification file name
        (-i infile or infile) or an input metafile name (-m metafile).

        See Section 2 of the X-13ARIMA-SEATS Reference Manual for more
        information on how to run X-13ARIMA-SEATS.
edd@don:~/git$ uname -a
Linux don 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:38:40 UTC 2015 i686 i686 i686 GNU/Linux
edd@don:~/git$ 
```

**Comment by christophsax** [comment]
I’ve created two pull requests with the win and mac binaries and downloaders.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by christophsax** [comment]
So I adjusted 'seasonal' to depend on 'x13binary'. To install the latest version on any platform:
```
devtools::install_github('x13org/x13binary')
devtools::install_github('christophsax/seasonal', ref = "x13download")
```

**Comment by eddelbuettel** [comment]
Awesome. I hope to able to take a look later.

**Comment by christophsax** [comment]
Well done, thanks a lot, Dirk!
