### ISSUE TITLE
Suggesting x13binary?

### ISSUE THREAD

**Issue by christophsax** [christophsax/seasonal#133]
An experiment [here](https://github.com/christophsax/seasonal/tree/feature/x13binary-suggests) where seasonal `Suggests:` x13binary, rather than `Depends:` on it. 

- Users with R < 3.2 could still go on to use seaonal as they were used to.
- For newer versions, a message will be droped on startup, suggesting to install x13binary.

The downside is that we have to install two packages now:

install.package('x13binary', 'seasonal')

Dirk @Eddelbuettel, what do you think?

**Comment by eddelbuettel** [comment]
Not a bad idea to not force it.   On the other hand we could argue that seasonal _really_ needs it.  And once we have x13binary on CRAN soon, why not depend on it?  I think I can see it both ways.  

What do you prefer right now?  What downside do you see?   And ... why would there be a 3.2 dependency?   _All_ of CRAN goes to .../3.2/... right now because installation of fresh packages is always at the current R release level.

**Comment by christophsax** [comment]
Sorry I misread your comment [here](https://github.com/x13org/x13binary/issues/16#issuecomment-169207361), where you were saying it would need 3.2. You were referring to the drat repo and not to x13binary in general. I then gave it a test on 3.1, were it failed for some reason and took it as confirmation. Will have a look at that error again.

So I thought R >= 3.2 is a too strong requirement. Of course, without that, `Depends:`is fine. We can keep it as a fallback plan.

**Comment by eddelbuettel** [comment]
Yes. It is entirely "us" (ie me) with drat repo, or really @gka for being on a older R which only look in 3.1/

For our purposes Depends: is indeed better.  But we need to figure our how to fail gracefully. Gregor also mentioned when we spoke on the spoke that `x13ashtml` does _not_ work for him on the command-line (no Fortran library) but works from R (which makes sense as R provides libgfortran as it needs it).

Macs are weird ...

**Comment by christophsax** [comment]
My problems with R 3.1 were due to missing `setInternet2()` under Windows. Closing this thread for now.
