### ISSUE TITLE
integration with {forecast}

### ISSUE THREAD

**Issue by ellisp** [christophsax/seasonal#149]
As per https://github.com/robjhyndman/forecast/issues/216 it would be convenient if objects created by X13 interfaced with the {forecast} package so (for example) one could use the plot methods from {forecast}.  One way to do this might be, suggested in that link, to create a forecast.xxx method for objects that have been fit with X13-SEATS-ARIMA which returns an object of class forecast.  

This may be on your radar, or even done already; or I could give it a go and do a PR if you're interested.

**Comment by christophsax** [comment]
Thanks. In a way, I would like to avoid having a huge dependency for such a small feature. Let me have some more thoughts about it. 

This would be even more useful together with `robust.seas` (a first draft is [here](https://github.com/christophsax/seasonal/blob/feature/robust.seas/R/robust.seas.R). It runs through all cases of your forecast competition — in less than half the time of `auto.arima`, but with results even worse than the ones reported by you). I would like to work a bit on that to see if there is a compelling case why you want to use X-13 for pure forecasting at all.

First need to get out a bug fix release, x13binary is already out.

**Comment by christophsax** [comment]
Just [learned](http://robjhyndman.com/hyndsight/forecast-v7-2/) about a new `seasadj` generic in the forecast package. Could be useful as well.

**Comment by christophsax** [comment]
The function would be rather simple. 

```
forecast.seas <- function(m, h = 36, level = 95){
  if (length(level) != 1) stop("compute a single CI only")
  m <- update(m, forecast.maxlead = h, forecast.save = "forecasts", forecast.probability = level / 100)
  fct <- series(m, "forecast.forecasts")
  m$mean   <- fct[, 'forecast']
  m$upper  <- fct[, 'upperci']
  m$lower  <- fct[, 'lowerci']
  m$level <- 90
  m$method <- "X-13ARIMA-SEATS"
  class(m) <- "forecast"
  m
}

library(seasonal)
m <- seas(AirPassengers)
plot(forecast(m, h = 50, level = 80)) 
```

<img width="490" alt="screen shot 2016-12-23 at 23 28 17" src="https://cloud.githubusercontent.com/assets/1390827/21458261/a53c4a6a-c967-11e6-8e37-6da839c8c012.png">

But is there much use for this? Ok, I get another plot. But should we really force the user to install a big package such as `forecast` for this? 

We probably should just give up on this. If you really have a need for the functionality, use the example.

**Comment by ellisp** [comment]
Sure, I thought it had been closed a while back.
