### ISSUE TITLE
Windows Vista OS, R (3.2.3) problem during loading seasonal package

### ISSUE THREAD

**Issue by dguariniello** [christophsax/seasonal#156]
I install  the seasonal package and get this warning in the instalation of the package x13binary: 
**Warning: unable to move temporary installation ‘C:\Users\Daniela\Documents\R\win-library\3.2\file159063ef699c\x13binary’ to ‘C:\Users\Daniela\Documents\R\win-library\3.2\x13binary’**
When I try to load the seasonal package I get this error:
**Error : .onLoad failed in loadNamespace() for 'seasonal', details:
  call: loadNamespace(name)
  error: there is no package called ‘x13binary’
Error: package or namespace load failed for ‘seasonal’**
On 1st march there has been an update of the x13 binaries, may be there is a problem with that.
I have installed before in an other computer (with windows 7 and the same R) and I had no problems.
Thank you.
Daniela.

**Comment by christophsax** [comment]
Can you try to just install `x13binary` and copy paste the output here? There should be some additional error messages (hopefully).

```
install.packages("x13binary")
```

**Comment by dguariniello** [comment]
No, does not work, it gives the same error
(Warning: unable to move temporary installation
‘C:\Users\Daniela\Documents\R\win-library\3.2\file159063ef699c\x13binary’ to
‘C:\Users\Daniela\Documents\R\win-library\3.2\x13binary’). I All so tried downloading
from the CRAN and installing from the zip.I could install it but in the  R version
3.1 but I had to download from the Census win13 and set the path manually.



Thank you.

Date: Sun, 6 Mar 2016 17:02:05 -0800

**Comment by christophsax** [comment]
Hmmm. Downloading manually and setting `X13_PATH` manually would be the recommended workaround, so good if *that* worked. This should also be pointed out when loading the latest CRAN version of seasonal. 

The underlying issue for failing must be something particular with your system, perhaps some restrictions on the library directory or some size limit on the downloads? Or with Vista, but find this hard to imagine. This is quite difficult to track down without access to the computer.
