### ISSUE TITLE
observation on forecast of seasonal factors

### ISSUE THREAD

**Issue by aranryan** [christophsax/seasonal#157]
I'm using seasonal to estimate monthly seasonal factors. I'm particularly interested in being able to use forecasts of the seasonal factors. I recently noticed that beyond 24 months, the seasonal factors tend to explode. 

The following provides reproducible example. In the output, I would have expected the seasonal factors forecast for 1963 in mmod2 would remain in the range of 0.4 to 1.4, but it jumps to 30 in January 1963 and quickly goes into the hundreds. For example, for Dec 1963, I obtain a value of 131.2, which is a world apart from the seasonal factors for previous Decembers (e.g. Dec 1962 at 0.4, Dec 1961 at 0.89).

Based on code from Example 7.14 at http://www.seasonal.website/examples.html#seats
```
library(seasonal)
library(xts)

mmod1 <- seas(AirPassengers, 
     regression.aictest = "td",
     outlier.types = c("ao", "ls", "tc"),
     forecast.maxlead = 36
)
# accessing s16 as combined seasonal factors
tail(as.xts(series(mmod1, "s16")), 48)
```

Same code, but with line added to append forecast
```
mmod2 <- seas(AirPassengers, 
              regression.aictest = "td",
              outlier.types = c("ao", "ls", "tc"),
              forecast.maxlead = 48,
              seats.appendfcst="yes"
)
tail(as.xts(series(mmod2, "s16")), 48)
```
I'm likely to only be using the first 24 months of forecasted seasonal factors. But I raise the observation because I might learn some other setting that I'm using incorrectly.

**Comment by christophsax** [comment]
I had the same problem once, and contacted the Census on the matter. Now they released a new version (Build 26, [changes](https://www.census.gov/srd/www/x13as/releaseNotes.html)), and - hooray!! - it seems to be fixed. I have just re-run your example and everything looks fine.

A new version of the binary providing `x13binary` package is on CRAN now, which includes Build 26. Simply update, and you should be fine:

```
install.packages("x13binary")
```

**Comment by aranryan** [comment]
Thanks for the tip. The code as I originally posted is working for me. Now the issue occurs when I set the forecast.maxlead at 48 (from 36, as originally posted). It seems that maybe that argument gets frozen in the x13binary in some way, as the text in my original comment still describes the situation. In any case, it if works for you when set at 48, and the Dec. 1964 value seems reasonable, it seem to be an issue on my end.

I've updated to:
x13binary version 0.1.2
seasonal version 1.2.1
R version 3.2.3

**Comment by christophsax** [comment]
You are right. The one with lead 48 is still wrong. 

What I did back then was to use X-11, rather than SEATS. This works like a charm:

```
mmod3 <- seas(AirPassengers, 
              regression.aictest = "td",
              outlier.types = c("ao", "ls", "tc"),
              forecast.maxlead = 48,
              x11.appendfcst="yes"
)

series(mmod3, "x11.adjustfac")
```
