### ISSUE TITLE
Not supported on the newest version

### ISSUE THREAD

**Issue by DanniGG** [christophsax/seasonal#159]
Hi there.
Is there any chance that this package will be supported on version 3.2.2? I get the following error when trying to install the package:  "package ‘seasonal’ is not available (for R version 3.2.2)".

**Comment by christophsax** [comment]
It is supported. Probably another problem, unrelated to seasonal. Have you tried installing it from source?

```
install.packages("seasonal", type = "source") 
```

**Comment by DanniGG** [comment]
Yes, it gives me the same error as before.
I am running Linux, btw. Could that be the issue?

**Comment by christophsax** [comment]
No, it works fine on Linux. It's something with your setup, not with seasonal. Can you install other packages?

**Comment by christophsax** [comment]
perhaps the second answer [here](http://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa)...

**Comment by DanniGG** [comment]
I can install other packages just fine :/

Thanks for sharing the article. I tried the different methods but have still not had any luck.

**Comment by mbannert** [comment]
@DanniGG you might want to try to install directly from github. I really feel this is a package / repo issue as opposed to a seasonal problem. For me it works just fine on `Wooden Christmas Tree aka 3.2.3` for both my local OSX and my RHEL driven R Studio Servers. Plus even Windows works...
