### ISSUE TITLE
Not compatible with `x13as`

### ISSUE THREAD

**Issue by Neil-Schneider** [christophsax/seasonal#169]
I also ran into [this](http://stackoverflow.com/questions/37157877/r-x13-arima-seasonalseas-error/) problem also. 

```
> a <- ts(rnorm(100), start = 2000, frequency = 12)
> seas(a)
Error in x[[2]] : subscript out of bounds
```

This appears to be an issue for anyone who has defined their own path to **X-13ARIMA-SEATS** and does not have `x13ashtml` binary in that folder. The `x13as` binary produces a `iofile_profiler` file without a file extension. This causes the `subscript out of bounds` error when `seas` attempts to split the file names [here](https://github.com/christophsax/seasonal/blob/master/R/seas.R#L382).

**Comment by christophsax** [comment]
Thanks. This would be an easy fix. However, I want to get rid to the x13as support in a future version. The latest version of seasonal (1.3) gives a warning. Is there a reason why you are not using `x13ashtml`?

**Comment by Neil-Schneider** [comment]
I had no reason for using `x13as` over `x13ashtml`. It just happened to be the version I originally downloaded. I am now using `x13ashtml`.

**Comment by christophsax** [comment]
Closing this one. `x13as` will become unsupported in one of the next releases.
