### ISSUE TITLE
including Japanese public holidays

### ISSUE THREAD

**Issue by Hergie** [christophsax/seasonal#170]
Hello,
I try to do seasonal adjustment using Japanese holidays. I try to use this adjustment when seasonalising `AirPassengers`.  I create Japanese public holidays using the package `Nippon`:

```
library(Nippon)
hol<-NULL # Output vector

for (y in 1949:1960) {
  hol<-c(hol, jholiday(y))
}

hol<-as.Date(hol)
```

However, the `genhol` function gives the following error:

```
> genhol(hol)
Error in cut(event.st.added, by, labels = F) : 
  object 'event.st.added' not found
```

What might be the issue?

Thank you!

**Comment by christophsax** [comment]
`genhol` seems not to work with *multiple occurrences of a date during a year*. Need to think about if this should be possible or if an error should be dropped.

From a seasonal adjustment point of view, most of your holidays don't need to be modelled, as they are fixed, not moving. Only use `genhol` with holidays that are moving between months, such as **Easter**, **Chinese New Year**, or **Diwali**. Not sure if there are any such Japanese holidays, but would be interested. If there is an important one, I would also like to include the dates in seasonal.

The following works, but produces a simple April regressor. This effect will be captured by standard seasonal adjustment. No modelling needed.


```
library(Nippon)
hol <- NULL # Output vector

for (y in 1949:1960) {
  hol<-c(hol, as.character(jholiday(y)))
}

hol1 <- as.Date(hol[names(hol) == "The Emperor's Birthday"])
library(seasonal)
genhol(hol1)
```
