### ISSUE TITLE
data object exp causing conflicts?

### ISSUE THREAD

**Issue by ellisp** [christophsax/seasonal#175]
I think the data object `exp` (monthly exports and imports of China) is causing conflicts by overwriting base::exp().  Is it newly added? (I only noticed a problem today).  Is it too late to give it another name?  I thought it might be causing https://github.com/ellisp/ggseas/issues/15 (although I don't know why I only have it on my Windows machine, not Linux; and I can't see any calls I have to `base::exp` in `ggseas` that would do it).

**Comment by christophsax** [comment]
I am away from my laptop for another week, but check it out then. seasonal::exp has been there since the beginning, and I don't remember seeing it causing problems. If it really does, it is just an example series (with indeed a stupid name) and renaming should be easy.

**Comment by christophsax** [comment]
seems unlikely to me that https://github.com/ellisp/ggseas/issues/15 is caused by `seasonal::exp`. Since you are importing seasonal, it shouldn't conflict with `base::exp` anyway. Plus, if it would be an issue, we should see it on non-Windows platforms as well.

**Comment by ellisp** [comment]
Yes ellisp/ggseas#15 is definitely caused by something else - probably a version mismatch with ggplot2.

I think it would probably still be good not to have data called `exp`, but not exactly a priority...
