### ISSUE TITLE
x13binary and arm hardware

### ISSUE THREAD

**Issue by dashaub** [christophsax/seasonal#195]
When I try to install "seasonal", the "x13binary" package is not available for armhf hardware. This includes raspberry pi, many Chromebooks, and other system on a chip computers running Linux.
```
** package 'x13binary' successfully unpacked and MD5 sums checked
Unknown architecture: armv7l. Exiting.
```
I downloaded the source package from CRAN and ran `R CMD check` but the log files did not contain any additional helpful information. Any ideas where to start troubleshooting? EDIT: since it appears this package merely downloads the US Census binary, so maybe it is not even possible.

**Comment by christophsax** [comment]
x13binary downloads our builds of X-13 from the [x13prebuilt](https://github.com/x13org/x13prebuilt) repo, not from the Census. 

You could try if one of the linux binaries (32 or 64) of X-13 does work on your platform. Try on the shell, using a  [standard spec file](https://github.com/christophsax/seasonal/blob/master/inst/tests/Testairline.spc).

If it does, a small edit in the 'configure' script of x13binary would do the trick. If it doesn't, you probably have to compile the X-13 fortran code on your machine, which may work or not, but will be quite cumbersome. Here is how to compile it for [ubuntu](https://github.com/christophsax/seasonal/wiki/Compiling-X-13ARIMA-SEATS-from-Source-for-Ubuntu).

**Comment by dashaub** [comment]
x84_64 and x86_32 binaries won't work. Building this myself is easy enough, but I'd like to add prebuilt binaries to x13prebuilt so this all works smoothly automatically. The next release v7.4 of the popular "forecast" package will import "seasonal", so the package will become installable automatically if armhf isn't added. I'm looking around the x13prebuilt and x13binary repos to address this and will probably have some questions..

**Comment by dashaub** [comment]
@christophsax @eddelbuettel Adding this looks fairly straightforward.
* Added armv7l to known architecture in configure in "x13binary". PR [here](https://github.com/x13org/x13binary/pull/41)
*  Compiled the binary and placed it in the armv7l directory in "x13prebuilt". The build script was failing due to two errors (First, mkdir failed after tempfile created the file directory, and second extracting the gz failed since the archive is apparently just a tar), so I also modified it. PR [here](https://github.com/x13org/x13prebuilt/pull/7)

Anything else?

**Comment by eddelbuettel** [comment]
> The next release v7.4 of the popular "forecast" package will import "seasonal",

Interesting.  We may need to rethink the scripts and allow for the build for any flavour of Linux, really.

**Comment by dashaub** [comment]
I could see the "x13prebuilt" build script being rewritten to cross compile for all the desired supported architectures to facilitate package version updates. I remember reading somewhere (blog posts, maybe r package devel mailing list) about the hoops you had to jump through and reasons for setting up the X13 packages like this but can't find them now. Any links?

**Comment by eddelbuettel** [comment]
It should be easy enough for Linux given that the compilers are there. And with my Debian hat on I am of course immediately thinking of the other 10 (hardware) architectures... all of which should be easy enough.  In that case we probably just build a x13 binary from the fortran files to x13binary will have to adapt.  We cross that bridge when we get there.

No major hoops. Census software has suitable license, we just had to write the scripts, set up the two tiered repos etc pp.  There should be some background in the README.md and maybe wiki ... and one day there may be a paper.  We'll see.

**Comment by dashaub** [comment]
Why even bother with the prebuilt Linux binaries? Why not just have the "x13binary" package download and compile from the Census if it isn't one of the "main" architectures.

**Comment by eddelbuettel** [comment]
That is what I said earlier.  It makes *perfect sense* to actually *have prebuilt binaries* for the *common* platforms.  But we currently exclude your more esoteric one, and a good plan would be to recognise the 'linux not intel32 or intel64' case.   I think we are on the same page, but getting diluted between two many messages.

**Comment by dashaub** [comment]
Ok, since this is spread across several repos, here might be a good place to talk about the big picture strategy and leave the specifics for elsewhere. For now, what do you think about adding prebuilt ARM binaries before doing a redesign on the "x13binary" configure script to fallback to compiling on other OS/architectures? I can fix the PR in "x13prebuilt" to use v1.1.26.

**Comment by eddelbuettel** [comment]
Sounds good.  Either a prebuilt binary, or (and that may actually be better) as a 'built on demand' option.

**Comment by christophsax** [comment]
I guess we can close this, thanks to both of you.
