### ISSUE TITLE
Problem with byte compiler in R 3.4

### ISSUE THREAD

**Issue by christophsax** [christophsax/seasonal#209]
I R 3.4, I got the following error, when calling `outlier` twice.

```r
library(seasonal)
m <- seas(AirPassengers)
outlier(m)
outlier(m)
# Error in stats::window(x = `*tmp*`, start = as.numeric(ol.time.R[[i]]),  : 
#    object '*tmp*' not found
```

Narrowing it down a bit it turns out this is probably caused by the new byte compiler which is turned on by default. So, here's the pure R problem:

```r
z <- AirPassengers

# this works
window(z, start =  c(1955, 1), end =  c(1955, 1)) <- NA

# this works not
for (i in 1) {
 window(z, start =  c(1955, 1), end =  c(1955, 1)) <- NA
}
# Error in stats::window(x = `*tmp*`, start = c(1955, 1), end = c(1955,  : 
#   object '*tmp*' not found


# turning off the byte compiler makes it working again
compiler::enableJIT(0)
for (i in 1) {
 window(z, start =  c(1955, 1), end =  c(1955, 1)) <- NA
}
```

If disabled *before* loading seasonal, this also fixes with the outlier problem:
```r
compiler::enableJIT(0)
library(seasonal)
m <- seas(AirPassengers)
outlier(m)
outlier(m)
```

**Comment by eddelbuettel** [comment]
Hairy. Suggest you post on r-devel.

**Comment by christophsax** [comment]
Seems to be a [R 3.4.0 issue](https://stat.ethz.ch/pipermail/r-devel/2017-May/074174.html). As a workaround, I got rid of the loop in `outlier()`. Should be also slightly more elegant now.

**Comment by eddelbuettel** [comment]
Nice. I clearly don't use `Map()` enough myself.  And I saw Tomas' follow-up so I guess you were just bitten by a regular garden-variety bug ...
