### ISSUE TITLE
Seasonal object returns week coefficients from monthly series. 

### ISSUE THREAD

**Issue by Diego-MX** [christophsax/seasonal#213]
Hello.  
I am using `seasonal` to remove outlier observations from transaction data provided by Mexican Bank Commission.   
The issue that I've come across is that I'm supplying a monthly time series, and when I see the result it seems to have been treated weekly.    
I hope this is an easy example to replicate.  I have saved a distilled data_frame in  [this repo](https://github.com/opintel/indice-de-actividad-economica/)... which is in Spanish, sorry. 
```
data_url <- "https://raw.githubusercontent.com/opintel/indice-de-actividad-economica/master/data/cnbv/processed/grupos_municipios_prex11.csv"
download.file(data_url, "temp.csv")

temp_df <- read_csv("temp.csv")

ts_0 <- temp_df %>%  
  filter(CVEMUN  == "01001") %$%  
  ts(banamex, start = c(2011, 4), frequency = 12)
```
After printing `ts_0`, one can see the montly reference in the headings. 
```
> ts_0
        Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct
2011                      276448 284070 262111 276955 273486 269390 263270
2012 264039 253287 284009 269911 288011 284918 286687 283552 268579 269502
2013 268193 251654 281964 288220 302899 280328 287026 294981 267889 287423
...
```
But after applying a simple season filter, the references become weekly. 

```
> seas_0 <- seas(ts_0, x11 = "")
> seas_0

Call:
seas(x = ts_0, x11 = "")

Coefficients:
              Mon                Tue                Wed  
       -0.0089986          0.0016411         -0.0103554  
              Thu                Fri                Sat  
        0.0001765          0.0251538         -0.0037120  
       Easter[15]  MA-Nonseasonal-01     MA-Seasonal-12  
       -0.0485333          0.2669196          0.6288913  
```
I apologize if this is a basic feature of handling the time series.  However, I did go through the `seasonal` vignette -which handles seasonal matters but is not seasonal =P , and I didn't find anything related.  
Thank you for your help and for making this tool available.  
Best regards.

**Comment by christophsax** [comment]
There is nothing wrong here. By default, seasonal uses:
```r
regression.aictest = c("td", "easter")
```
which means it performs an AIC test for weekday effects. In your series, it is detecting and correcting for weekday effects, i.e. it counts the number of Mondays, Tuesdays etc. *per month* and removes its effect from the series.

You get the final *monthly* series like this:

```r
final(seas_0)
```

**Comment by Diego-MX** [comment]
Wow, that's so ellaborate!  
Thanks for clearing this out.
