### ISSUE TITLE
SIGTRAP, Symbol not found and Status 133 errors

### ISSUE THREAD

**Issue by pollytatouin** [christophsax/seasonal#214]
Hi,

I just installed your package which looks very promising, but when I try to run a basic seasonal adjustment on Airpassengers, I get the following errors:

` m<-seas(AirPassengers)
sh: line 1:  2317 Trace/BPT trap: 5       /Library/Frameworks/R.framework/Versions/3.2/Resources/library/x13binary/bin/x13ashtml /var/folders/yg/dmjyhs4122n5gj7wnfjz20cr0000gn/T//RtmppckY9s/x1390068ba6f6a/iofile -n -s 2> /dev/null
dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/x13binary/bin/../lib/libgfortran.3.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/x13binary/bin/../lib/libgfortran.3.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Program received signal SIGTRAP: Trace/breakpoint trap.

Backtrace for this error:
#0  0x1301e4579
#1  0x1301e3945
#2  0x7fff962c8529
Erreur : X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
De plus : Warning message:
l'exécution de la commande '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/x13binary/bin/x13ashtml /var/folders/yg/dmjyhs4122n5gj7wnfjz20cr0000gn/T//RtmppckY9s/x1390068ba6f6a/iofile -n -s 2>/dev/null' renvoie un statut 133 `

I use R v. 3.2.3

Thanks !

**Comment by christophsax** [comment]
Hi, sorry for the delay. 

This must be something specific to your mac. Are you using a pre-Sierra version of OS-X? If so, which one?

What is your version of x13binary?

```r
packageVersion("x13binary")
```

Do you have the latest (`1.1.39.1`)? If not, try installing from CRAN and retry:

```r
install.packages("x13binary")
```

If you have the latest version, try it with the previous version:

```r
devtools::install_version("x13binary", version = "0.1.2", repos = "http://cran.us.r-project.org")
```

**Comment by pollytatouin** [comment]
Hi Christo,

I had the latest version of x13binary installed, so I installed the previous version as you suggested and it works perfectly! Thanks for the support.

polly

**Comment by christophsax** [comment]
Good to hear, but unclear why it is not working with the latest.

What is your version of macOS? 
(Click on the Apple on the upper left. Then 'About This Mac')

**Comment by pollytatouin** [comment]
El Capitan Version 10.11.6

**Comment by christophsax** [comment]
This is related to old Mac OS and should resolve itself over time. Closing for now.
