### ISSUE TITLE
Wrong dates for the Chinese New Year

### ISSUE THREAD

**Issue by MasakiOita** [christophsax/seasonal#219]
According to the [Hong Kong Observatory](http://www.hko.gov.hk/gts/time/conversion.htm) and [Wikipedia](https://en.wikipedia.org/wiki/Chinese_New_Year), the date of the Chinese New Year was Feb. 19 in 2015, and will be Feb. 16 in 2018.
However, the variable _cny_ stores the wrong dates "2015-02-18" and "2018-02-15" for these years.

**Comment by christophsax** [comment]
Thanks. Yes, that's true. Will change it.
