### ISSUE TITLE
Adjusted series

### ISSUE THREAD

**Issue by gumlese** [christophsax/seasonal#223]
First of all, thank you for an amazing package.

The issue I am having is that the final series produced by regARIMA does not have outlier adjustments applied. This is affecting outputs, like trend-cycle estimation and long-term trend extraction, later in the process. 

Take the following example using the electricity equipment time series from the fpp package. There is a level shift identified in January 2009 that should be shifting the final series down. I can extract an adjusted trend-cycle from the X13 html output, but there is no associated long term trend.

`library(fpp)`
`m <- seas(elecequip, outlier.types = "LS", seats.hpcycle = "YES", seats.save = "ltt")`
`plot(series(m,"a19"))`
`lines(final(m))`
`lines(series(m,"s12"))`
`lines(series(m,"ltt"))`

Cheers

Sean

**Comment by christophsax** [comment]
Sorry for the belated answer.

Not sure if I got the problem, but outlier are removed before modelling the ARIMA model but are reapplied later on, so they *are* part of the final series.

This is why the final series has the same level as the original one both after and before the level shift.

``` r
library(seasonal)
library(fpp)
#> Loading required package: forecast
#> Loading required package: fma
#> Loading required package: expsmooth
#> Loading required package: lmtest
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: tseries
m <- seas(elecequip, outlier.types = "LS", seats.hpcycle = "YES", seats.save = "ltt")
plot(m)
```

![](https://i.imgur.com/KnoOfqA.png)

**Comment by gumlese** [comment]
Hey Christoph,

Thanks for the response. Sorry, I didn't present my issue clearly!

I see how the outliers are removed and reintroduced for the final set of series from SEATS after being identified from the ARIMA model. However, shouldn’t the outliers also be removed from the trend-cycle series feeding into the HP filter to extract the long-term trend (and subsequently re-introduced)?

Sean

**Comment by christophsax** [comment]
I haven't worked with the SEATS HP decomposition so far, and just did some quick experiments, so take the following with a grain of salt.

The way I see it is that outliers are removed during for the SEATS decomposition, and added to the final trend decomposition. If you do the HP cycle/longterm decomposition, the outliers are added to the cycle. So the actual HP decomposition looks like this:

``` r
library(tsbox)  # devtools::install_github("christophsax/tsbox")
suppressMessages(library(fpp))
library(seasonal) 
m <- seas(elecequip, outlier.types = "LS", seats.hpcycle = "yes", seats.save = "ltt")

ts_plot(
  `Adjusted Overall Trend` = series(m, "seats.trend") / series(m, "regression.outlier"),
  `Adjusted Cycle` = series(m, "seats.cycle") / series(m, "regression.outlier"),
  `Long Term Trend` = series(m, "seats.longtermtrend")
)
```

![](https://i.imgur.com/E4Ayc0p.png)

Outliers are then added to to the cycle and the overall trend, to produce the final series. Does that make sense?

**Comment by christophsax** [comment]
Seems silly that the long term trend is going down when everything is going up? Yes. Perhaps you need to ask people at the Census.

**Comment by christophsax** [comment]
Sorry, seems not to be true what I said earlier: The HP decomposition is really just the decompostion of the `seats.trend` series (which includes the outlier) into a longterm and a cycle component, nothing else. Here is an (almost) reproduction with the HP filter from the `mFilter` package:

``` r
library(tsbox)  # devtools::install_github("christophsax/tsbox")
suppressMessages(library(fpp))
library(seasonal) 
library(mFilter)
m <- seas(elecequip, outlier.types = "LS", seats.hpcycle = "yes", seats.save = "ltt")

ts_plot(
  `Long Term Trend mfilter` = mFilter(series(m, "seats.trend"), filter="HP")$trend,
  `Long Term Trend X13` = series(m, "seats.longtermtrend"),
  `Cycle mfilter` = mFilter(series(m, "seats.trend"), filter="HP")$cycle + 100,
  `Cycle X13` = series(m, "seats.cycle")
)
```

![](https://i.imgur.com/w77mMQU.png)

**Comment by gumlese** [comment]
Hey Christoph, this issue can be closed because it is a matter for the US Census program. I talked to the US Census a while back and they agreed the trend-cycle decomposition should not have outliers included. Maybe this will flow through to the seasonal package one day but mfilter is sufficient.
