### ISSUE TITLE
saving tables of seats spec

### ISSUE THREAD

**Issue by giancarlobruno** [christophsax/seasonal#229]
I am trying the following example, but the requested series are not available although provided for in x13-arima-setats manual. Thank you.

aa <- seas(AirPassengers, seats.save="se3")
series(aa,'se3')

**Comment by christophsax** [comment]
Thanks for the report, @giancarlobruno

Where do you see `se3` it in the manual? I see:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1390827/56116996-732b5280-5f67-11e9-88ed-d870fd102446.png">

Am I missing something?

**Comment by giancarlobruno** [comment]
Hi @christophsax I am referring to the manual accessible here:
https://www.census.gov/ts/x13as/docX13ASHTML.pdf
page 167 table 7.31, last two lines, it seems they lack from the image sent

**Comment by christophsax** [comment]
Thanks. Yes, indeed, there seems to be a difference betgween https://www.census.gov/ts/x13as/docX13ASHTML.pdf and https://www.census.gov/ts/x13as/docX13AS.pdf:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/1390827/56135046-3293ff00-5f90-11e9-9494-d2f3e24f964b.png">

which differs from the one in `docX13AS.pdf`:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1390827/56135212-84d52000-5f90-11e9-9909-1bab921f20ae.png">

I agree that `docX13ASHTML.pdf` is the relevant one and this should be included. 

This is related to #216. Ideally, this is achieved by automatically scraping the manual (or another source) for changes and update `SPECS` accordingly. 

Alternatively, a quick fix would be to just add the two entries here. Would that be of any use to you?

**Comment by giancarlobruno** [comment]
I tried to add the two entries, but I did not succeed. This is my example code:

```
library(seasonal)
SPECS <- rbind(SPECS,
      data.frame(long=c('seats.irregularoutieradj','seats.seasonaladjoutlieradj'),
                 short=c('se2','se3'),
                 spec=c('seats','seats'),
                 is.save=c(TRUE,TRUE),
                 is.series = c(TRUE,TRUE),
                 requires =''))
aa <- seas(AirPassengers)
print(series(aa,'se3'))

```

**Comment by christophsax** [comment]
Haha, I just tried exactly the same. This may have worked in an earlier version, but it is not using `SPECS` from the global environment.

I adjusted it on a branch (you can get it from there):

``` r
# remotes::install_github("christophsax/seasonal", ref = "missing-seats-output")
library(seasonal)

aa <- seas(AirPassengers)
series(aa,'se3')
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1949 0.9978869 1.0036268 0.9959432 1.0064547 1.0032599 0.9991512 0.9931991
#> 1950 0.9772990 1.0143442 1.0040732 0.9955285 0.9873114 1.0039066 1.0043885
#> 1951 1.0125750 0.9952516 1.0081278 1.0021809 0.9999670 0.9897871 1.0049463
#> 1952 1.0087075 1.0158050 0.9873031 0.9861140 0.9980297 1.0186498 0.9880860
#> 1953 0.9912350 0.9947211 1.0005116 1.0184489 1.0089229 0.9877639 0.9920905
#> 1954 1.0029635 0.9705965 1.0215815 0.9912362 1.0033918 0.9968589 1.0110834
#> 1955 1.0003052 1.0085385 0.9947372 0.9991927 0.9954940 1.0019323 1.0074804
#> 1956 1.0014826 0.9982494 0.9924657 1.0058593 1.0009030 1.0045373 0.9958340
#> 1957 1.0041191 0.9980907 1.0049317 0.9971123 1.0015321 1.0002849 0.9990184
#> 1958 1.0016264 1.0022736 1.0015465 0.9866277 0.9944425 1.0065432 1.0002443
#> 1959 1.0017984 0.9999855 1.0072671 0.9997523 1.0021650 0.9919297 1.0038551
#> 1960 1.0000414 0.9988627 0.9817273 1.0116130 1.0043580 0.9986397 0.9996320
#>            Aug       Sep       Oct       Nov       Dec
#> 1949 0.9982878 1.0038095 0.9963177 1.0091445 1.0037240
#> 1950 0.9995417 1.0127904 0.9953823 0.9796029 1.0028158
#> 1951 0.9973832 0.9941332 1.0014978 1.0130413 0.9862244
#> 1952 1.0077362 0.9871569 1.0081746 0.9988540 1.0079834
#> 1953 1.0016085 1.0008089 1.0090125 0.9941502 1.0047979
#> 1954 0.9924817 1.0034451 0.9901684 1.0078023 0.9956950
#> 1955 0.9903475 1.0097154 0.9953174 0.9926496 1.0097059
#> 1956 1.0023391 0.9947044 0.9994686 1.0058925 0.9912527
#> 1957 0.9971072 1.0056479 0.9989829 1.0026532 0.9999635
#> 1958 1.0128229 0.9878958 1.0100433 0.9926693 0.9908408
#> 1959 1.0001336 1.0033226 0.9906488 1.0020419 1.0111192
#> 1960 1.0000148 0.9965318 1.0048485 1.0015660 0.9958384
```

<sup>Created on 2019-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by giancarlobruno** [comment]
Thank you
