### ISSUE TITLE
Error: X-13 run failed Errors: - A model estimation error has occurred during AIC testing within the automatic model identification procedure. The error message appears below. - Estimation failed to converge -- maximum iterations reached

### ISSUE THREAD

**Issue by LinyiGuo96** [christophsax/seasonal#241]
Question description: I want to obtain the preprocessed datasets(after applying 'b1') and change multiplicative models into additive models. And I simulate 1000 time-series datasets at length 180(15 yrs) before. My code is the following:

```
# define a function for outliers and log-transformation
preprocess <- function(x11) {
  
  if(transformfunction(x11) == 'log') 
    data <- log(series(x11, 'b1'))
  else
    data <- series(x11, 'b1')

  return(data)
}


# build model list
# where 'datalist' is the list of 1000 original datasets
x11list <- lapply(datalist, function(x) seas(x, x11=''))


# obtain the preprocessed datalist denoted as Datalist
Datalist <- lapply(x11list, preprocess)
```

And then I got this: 

*Error: X-13 run failed Errors: - A model estimation error has occurred during AIC testing within the automatic model identification procedure. The error message appears below. - Estimation failed to converge -- maximum iterations reached*

**Comment by LinyiGuo96** [comment]
Well this error is due to `x11list <- lapply(datalist, function(x) seas(x, x11=''))' not the last line, sorry.

**Comment by LinyiGuo96** [comment]
And another thing is if my datalist is not very huge, then there is no error anymore.

**Comment by christophsax** [comment]
Sorry for the late response. Have you tried wrapping the call in `try()`?

```r
x11list <- lapply(datalist, function(x) try(seas(x, x11='')))
```

Some series cannot be processed by X13 and will fail.
