### ISSUE TITLE
"Error: X-13 run failed  Errors: - Argument name "e" not found"

### ISSUE THREAD

**Issue by jessi-meadows** [christophsax/seasonal#242]
Thank you so much for making this package! It is really helpful. However, I've bee repeatedly running into the error:
"Error: X-13 run failed
Errors:
- Estimation failed to converge for automatically identified model when convergence tolerence reset to 0.100000E-04. Rerun program trying one of the following: Allow more iterations (set a larger value of maxiter).Try a different model or different modeling options.  See Section 5 of the X-13ARIMA-SEATS Reference Manual for more discussion."

and I found your thread about setting `estimate.maxiter` to a larger number. Currently, I have: 
`seas(x1,outlier = NULL, x11 = "",estimate.maxiter=10000)` 
(after repeatedly running higher iterations and getting the same error) and now I am getting the error: 

Error: X-13 run failed

Errors:
- Argument name "e" not found

However, the code worked with `estimate.maxiter = 99999`. Is there a way to set the maximum iterations higher than 99999?

**Comment by christophsax** [comment]
Could you please provide a reproducible example. See here:

https://github.com/christophsax/seasonal/wiki/Creating-a-Reproducible-Example

Thanks a lot!
