### ISSUE TITLE
seas function issue

### ISSUE THREAD

**Issue by badrqst** [christophsax/seasonal#243]
I've used seas function for bank deposits time series, that are given in billions (eg. 10095824810). However, I've got an error:

At line 174 of file prttbl1.f
Fortran runtime error: End of record

Error termination. Backtrace:
#0  0x12657f579
#1  0x126580235
#2  0x126580999
#3  0x12664769b
#4  0x12664fd87
#5  0x126650d52
#6  0x126649afc
#7  0x106229250
#8  0x10603094e
#9  0x1062973f7
#10  0x10600feef
#11  0x106000915
#12  0x10631c539
#13  0x106344147
#14  0x105fd0706
#15  0x105fd238a
Error: X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
In addition: Warning messages:
1: In system(paste(x13.bin, file, flags), intern = TRUE, ignore.stderr = TRUE) :
  running command '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/x13ashtml /var/folders/6d/wy8_4m8n7n7715yqlx271zb00000gn/T//RtmpIvJhgf/x1377ba146625b8/iofile -n -s 2>/dev/null' had status 2
2: In system(paste(x13.bin, file, flags), intern = TRUE, ignore.stderr = FALSE) :
  running command '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/x13ashtml /var/folders/6d/wy8_4m8n7n7715yqlx271zb00000gn/T//RtmpIvJhgf/x1377ba146625b8/iofile -n -s' had status 2

My hypothesis was that numbers were too long and I've managed to overcome this issue by dividing the series by 10^9.

**Comment by christophsax** [comment]
Could you please provide a reproducible example. See here:

https://github.com/christophsax/seasonal/wiki/Creating-a-Reproducible-Example

Thanks a lot!
