### ISSUE TITLE
Run on macOS older than Sierra

### ISSUE THREAD

**Issue by manj0009** [christophsax/seasonal#244]
Hello, I am encountering issues with seas. Using the standard dataset "AirPassengers", I keep on getting a long message. Help?

#Seasonally adjust AirPassengers
library(seasonal)
AP <- seas(AirPassengers)

sh: line 1: 22772 Trace/BPT trap: 5       /Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/x13ashtml /var/folders/mr/qz_hb_wx2r30z09p0dg2ly_w0000gn/T//RtmpB8oktU/x13589ef4ed811/iofile -n -s 2> /dev/null
dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/../lib/libgfortran.3.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/../lib/libgfortran.3.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Program received signal SIGTRAP: Trace/breakpoint trap.

Backtrace for this error:
#0  0x123475579
#1  0x123474945
#2  0x7fff99450529
Error: X-13 has returned a non-zero exist status, which means that the current spec file cannot be processed for an unknown reason.
In addition: Warning message:
In system(paste(x13.bin, file, flags), intern = TRUE, ignore.stderr = TRUE) :
  running command '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/x13binary/bin/x13ashtml /var/folders/mr/qz_hb_wx2r30z09p0dg2ly_w0000gn/T//RtmpB8oktU/x13589ef4ed811/iofile -n -s 2>/dev/null' had status 133

**Comment by christophsax** [comment]
You are on MacOS Sierra, which is a few generations behind. It may be that the latest build of the binaries just does not work on this OS. 

Any chance you could update to a newer macOS?

Alternatively, you could try an older build of X-13 from [here](https://github.com/x13org/x13prebuilt/tree/master/v1.1.26/osx), but not sure if this will work.

**Comment by manj0009** [comment]
Hello Christopher,

I am on OS X El Capitan.

Best regards
Mambuna

**Comment by christophsax** [comment]
Can you try:

```r
 packageVersion("x13binary")

seasonal::checkX13()
```

**Comment by manj0009** [comment]
After using the package version, I still encountered the same problem and message.

**Comment by christophsax** [comment]
Yes, of course. But what is the output of the two commands?

**Comment by manj0009** [comment]
The output I get after the first command is [1] 1.1.39.2. The second one just provided a message and errors. I have attached a screen shot from the R console.

**Comment by christophsax** [comment]
Ah, I guess I understand the problem: You are on El Capitain, which is one version *older* than Sierra. One of the libraries complains that it is built for Mac OS X 10.12 (Sierra), so I don't think that will work, sorry.

Possibilities are to upgrade macOS or (perhaps) to use an old version of x13binary.

**Comment by manj0009** [comment]
Thank you very much and I am working on upgrading my OS.

Best regards
Mambuna
