### ISSUE TITLE
Calling Fortran compiled file from R using the seasonal package

### ISSUE THREAD

**Issue by FelipeCarrillo** [christophsax/seasonal#248]
This is not an issue, it is a question.
I was told that I can use the seasonal package to run a compiled Fortran file from R.
Can someone here help showing how to accomplish this task?
For example, I compiled using g95 on the command line like this: g95 fish.f -o fish.exe
Now how can I open fish.exe from R?
Thank you much.

**Comment by christophsax** [comment]
Hi @FelipeCarrillo 

No, you cannot use the seasonal package to compile Fortran. It uses binaries of software written in Fortran.
