### ISSUE TITLE
Musgrave asymmetric moving average asymmetric 

### ISSUE THREAD

**Issue by huangzhaor** [christophsax/seasonal#254]
I want to know how to implement Musgrave asymmetric moving average in X-11 .Does the source code in the seasonal package include this part? Or is this just an interface?

**Comment by huangzhaor** [comment]
If R is just an interface, can you tell me where I can download the source code？

**Comment by mbannert** [comment]
The original FORTRAN program is from the US Census Bureau. You can download it from here: 
https://www.census.gov/srd/www/x13as/ 

Binaries and source code should both be available.

**Comment by huangzhaor** [comment]
Thank you!

**Comment by huangzhaor** [comment]
https://www.census.gov/srd/www/x13as/
I can't go to this website, even if I hang up VPN. Is it still the address?

**Comment by christophsax** [comment]
The website works.
