### ISSUE TITLE
as.data.frame.seas is not exported from namespace

### ISSUE THREAD

**Issue by jdjohn215** [christophsax/seasonal#255]
I'm using `v1.7.1` installed from CRAN. 

The function `as.data.frame.seas` doesn't appear to be exported to the namespace.

    > seasonal::as.data.frame.seas
    Error: 'as.data.frame.seas' is not an exported object from 'namespace:seasonal'

I copy/pasted the function's code from [the R file](https://github.com/christophsax/seasonal/blob/master/R/as.data.frame.R), and it works great. I think there might just be some sort of namespace/roxygen issue happening.

Thanks for the very useful package.

**Comment by christophsax** [comment]
Isn't that the normal behavior of S3 methods? The generic is exported, but not the methods:

So this works just fine:

``` r
library(seasonal)
head(as.data.frame(seas(AirPassengers)))
#>         date    final  seasonal seasonaladj    trend irregular adjustfac
#> 1 1949-01-01 122.7133 0.9019909    122.7133 122.9732 0.9978869 0.9126963
#> 2 1949-02-01 124.7657 0.9542175    124.7657 124.3148 1.0036268 0.9457731
#> 3 1949-03-01 125.0734 1.0698054    125.0734 125.5828 0.9959432 1.0553807
#> 4 1949-04-01 127.5286 1.0023238    127.5286 126.7107 1.0064547 1.0115378
#> 5 1949-05-01 127.3584 0.9486743    127.3584 126.9446 1.0032599 0.9500745
#> 6 1949-06-01 126.1729 1.0762915    126.1729 126.2800 0.9991512 1.0699607
```

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


If you really want to call the method directly, you need to call `seasonal:::as.data.frame.seas`.

**Comment by jdjohn215** [comment]
Oh! My apologies. I misunderstood this distinction. Thanks for the explanation.
