### ISSUE TITLE
Bug in Date_ts

### ISSUE THREAD

**Issue by QiongJoanZ** [christophsax/seasonal#256]
The bug in seasonal:::Date_ts shifts the date back by 1 quarter when frequency is 4. This results in error in as.data.frame.seas method when coercing output of quarterly frequency into data.frame.

function (x) 
{
  f <- frequency(x)
  if (f == 12) {
    z <- as.Date(paste(floor(time(x)), cycle(x), "1", sep = "-"))
  }
  else if (f == 2) {
    z <- as.Date(paste(floor(time(x)), (cycle(x) - 1) * 
      6, "1", sep = "-"))
  }
  else if (f == 4) {
    z <- as.Date(paste(floor(time(x)), (cycle(x) - 1) * 
      3, "1", sep = "-"))
  }
  else {
    stop("unsupported frequency")
  }
  z
}

**Comment by christophsax** [comment]
The bug:

``` r
library(seasonal)
head(as.data.frame(seas(austres)))
#>         date    final  seasonal seasonaladj    trend irregular adjustfac
#> 1 1971-03-01 13068.94 0.9998747    13068.94 13069.25 0.9999770 0.9998747
#> 2 1971-06-01 13133.76 0.9997517    13133.76 13133.96 0.9999949 0.9997517
#> 3 1971-09-01 13196.46 1.0001469    13196.46 13195.35 1.0000634 1.0001469
#> 4       <NA> 13251.20 1.0002266    13251.20 13251.82 0.9999706 1.0002266
#> 5 1972-03-01 13305.32 0.9998785    13305.32 13305.30 0.9999942 0.9998785
#> 6 1972-06-01 13357.25 0.9997495    13357.25 13357.18 1.0000079 0.9997495
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by christophsax** [comment]
After fix:

``` r
library(seasonal)
head(as.data.frame(seas(austres)))
#>         date    final  seasonal seasonaladj    trend irregular adjustfac
#> 1 1971-04-01 13068.94 0.9998747    13068.94 13069.25 0.9999770 0.9998747
#> 2 1971-07-01 13133.76 0.9997517    13133.76 13133.96 0.9999949 0.9997517
#> 3 1971-10-01 13196.46 1.0001469    13196.46 13195.35 1.0000634 1.0001469
#> 4 1972-01-01 13251.20 1.0002266    13251.20 13251.82 0.9999706 1.0002266
#> 5 1972-04-01 13305.32 0.9998785    13305.32 13305.30 0.9999942 0.9998785
#> 6 1972-07-01 13357.25 0.9997495    13357.25 13357.18 1.0000079 0.9997495
```

<sup>Created on 2021-02-28 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
