### ISSUE TITLE
Question on seasonal adjustment 

### ISSUE THREAD

**Issue by shemkira** [christophsax/seasonal#257]
Hi! 
I'm trying to seasonally-adjust series in R by following spec:
seas(window(CLO,start=c(2015,9),end=c(2020,12)),
            arima.model=c(1,1,0,1,0,0),
            transform.function="log",
            regression.aictest=NULL)
But it gives the warning "Model used in SEATS is different: (0 2 1)(0 1 1)"
When I try to do it on http://www.seasonal.website/  there are no such a problem. Besides, when option 'auto search' is chosen it also gives (1,1,0)(1,0,0).
So I don't understand why R gives me this warning and why it can't make seasonal adjustment by my spec. Would you be so kind to explain me why this occurs? 
Thank you in advance

**Comment by christophsax** [comment]
Something is probably different between the two runs, it uses the same code otherwise. 

To understand better, could you create a reproducible example as explained here:

https://github.com/christophsax/seasonal/wiki/Creating-a-Reproducible-Example

**Comment by shemkira** [comment]
library(seasonal)
series=structure(c(302.214641176362, 306.445646152831, 309.939126518973, 
              311.984724753998, 313.700640740145, 315.77106496903, 318.265656382285, 
              320.207076886217, 321.712050147582, 322.548501477966, 323.193598480922, 
              324.938843912719, 328.123244583064, 331.010729135395, 333.39400638517, 
              334.72758241071, 335.330092059049, 336.034285252373, 337.075991536656, 
              337.817558718036, 338.189158032626, 338.392071527446, 338.831981220432, 
              339.848477164093, 341.309825615898, 343.221160639347, 344.353790469457, 
              344.939191913255, 345.111661509212, 345.491284336872, 346.044070391811, 
              346.52853209036, 346.736449209614, 346.771122854535, 346.875154191391, 
              347.672967046031, 349.237495397739, 351.053530373807, 352.317323083153, 
              352.845799067777, 353.269214026659, 353.728464004893, 354.329802393702, 
              354.932163057771, 355.322588437134, 355.322588437134, 355.535781990197, 
              356.424621445172, 357.743392544519, 359.174366114697, 360.323724086264, 
              360.575950693125, 360.503835502986, 360.503835502986, 361.044591256241, 
              360.827964501487, 361.080544076638, 361.152760185453, 361.333336565546, 
              362.308936574273, 363.975557682515, 365.395062357476, 366.30855001337, 
              366.30855001337), .Tsp = c(2015.66666666667, 2020.91666666667, 
                                         12), class = "ts")
series_sa=seas(series,
            arima.model=c(1,1,0,1,0,0),
            transform.function="log",
            regression.aictest=NULL)

**Comment by christophsax** [comment]
Thanks, I can see the working in R. Can you also send me the CSV you used, so I can check on www.seasonal.website?

**Comment by christophsax** [comment]
Ah, it may be simply that these messages are not displayed on the website. 

These are not errors. They indicate that SEATS uses its own model, rather than the one found by the regARIMA model search. If you don't like that and want to stick with your model, you can still go for X-11 (`x11 = ""`).

**Comment by shemkira** [comment]
The file is attached.
Oh, I see. Thanks! Than I'll try X-11
[clo.zip](https://github.com/christophsax/seasonal/files/6089555/clo.zip)
