### ISSUE TITLE
forecast for annual series incorrect date

### ISSUE THREAD

**Issue by duncanelliott** [christophsax/seasonal#264]
If I have the following time series of annual data (2005-2019), using the series function to extract the forecast reads the forecasts as 2019 rather than 2020 (which can be seen in out(m) )

y <- ts(c(41,39.8,40,40.5,37.8,37.3,34.6,36.1,37.1,32.9,35,33.4,34.7,36.2,38.1),freq=1,start=2005)

m <- seas(y,x11=NULL,seats=NULL,regression.aictest = NULL,forecast.maxlead=1)
fct <- series(m,"fct")

**Comment by christophsax** [comment]
Indeed, that looks wrong!
