### ISSUE TITLE
x13 binary file for Big Sur OS

### ISSUE THREAD

**Issue by stephenpg** [christophsax/seasonal#266]
Apologies if I'm being dumb here, but having an issue with seasonal on Big Sur - it doesn't seem to be able to find the binary file:
So for eg - (having previously installed seasonal, but just for illustration, get same error msg as below). It tells me where the binary file is, but it isn't there...
thanks for any steer!

```r
>install.packages("seasonalview")
also installing the dependencies ‘shinydashboard’, ‘openxlsx’

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/shinydashboard_0.7.1.tgz'
Content type 'application/x-gzip' length 323878 bytes (316 KB)
==================================================
downloaded 316 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/openxlsx_4.2.4.tgz'
Content type 'application/x-gzip' length 3361518 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/seasonalview_0.3.tgz'
Content type 'application/x-gzip' length 88692 bytes (86 KB)
==================================================
downloaded 86 KB


The downloaded binary packages are in
	/var/folders/8v/mlwp010n14s3l_s3hs6qt4cw0000gn/T//RtmpbTm3PX/downloaded_packages

> checkX13()
Binary executable file /var/folders/8v/mlwp010n14s3l_s3hs6qt4cw0000gn/T//RtmpbTm3PX/downloaded_packages/x13as or /var/folders/8v/mlwp010n14s3l_s3hs6qt4cw0000gn/T//RtmpbTm3PX/downloaded_packages/x13ashtml not found.
See ?seasonal for details.
```

**Comment by eddelbuettel** [comment]
So for starters:

- minimal beats extraneous: if you have an issue with installating `seasonal`, show us errors from _just installing it_ and two extraneous packages

- then do that step and try to break it down: what file gets downloaded? what is inside? where does it write to? In other words help me help you -- I do not have a Big Sur system, let alone a mac. You do. Make it easier for me to spot what may be wrong.

- maybe invest two minutes of you time into learning the formatting here to make it easier on our eyes; I will edit your post now

**Comment by stephenpg** [comment]
Thanks vm for the response - much appreciated. Apologies for the mess formatting; am still finding my way around R/the community etc.

There is no issue with installing seasonal. 

I thought perhaps, because it could not find the binary file from the get-go (in the address it said it had downloaded the file to), it might be that Big Sur was messing around with the path. I've seen other folk suggest that this is the case with other packages (e.g. with the sf package) and wondered if it was an issue that had been previously highlighted. 

As you suggested, I went looking in the terminal. This is fine - the T file exists, I can see it:

% open/var/folders/8v/mlwp010n14s3l_s3hs6qt4cw0000gn/T

But then I'm afraid I didn't know how to navigate past the // after the T directory, as in:

/var/folders/8v/mlwp010n14s3l_s3hs6qt4cw0000gn/T//RtmpbTm3PX/downloaded_packages/x13ashtml 

The T directory does not have any file named RtmpbTm3PX in it, though I can see. I also searched in all directories for x13ashtml but it does not show. 

Hope that's a bit clearer - thanks again for your help.

**Comment by christophsax** [comment]
I am on Big Sur, too. there is nothing particular about this OS.

Perhaps you could start with:

```r
install.packages("x13binary")
x13binary::checkX13binary()
```

And show us the output.

**Comment by stephenpg** [comment]
Thanks Christoph. Output:

x13binary is working properly

**Comment by christophsax** [comment]
An then, after a restart:

```r
seasonal::checkX13()
```

**Comment by stephenpg** [comment]
Thanks. This is when it goes wrong:

Path 'YOUR_X13_DIRECTORY' specified but does not exists.

**Comment by christophsax** [comment]
Have you previously set your `X13_PATH` manually? You need to make sure this is not set. Check in *a fresh* R Session:

```
Sys.getenv("X13_PATH")
```

If there is something other than `""`, you can override it by setting it to `""` **before** loading seasonal:

```r
Sys.setenv(X13_PATH = "")
library(seasonal)
seasonal::checkX13()
```

**Comment by christophsax** [comment]
I suspect you have run the following line from `?seasonal` as it is:

```
write('Sys.setenv(X13_PATH = "YOUR_X13_DIRECTORY")', file = "~/.Rprofile", append = TRUE)
```

But `YOUR_X13_DIRECTORY` was meant as a placeholder, where you would put an actual directory! But then, thanks to x13binary, you don't have to do this - seasonal works out of the box, unless you are in a weird corporate environment.

Edit `~/.Rprofile` in a text editor and remove `Sys.setenv(X13_PATH = "YOUR_X13_DIRECTORY")'` and you should be good. 

But check my previous post, especially `Sys.getenv("X13_PATH")` first to see if I am right.

**Comment by stephenpg** [comment]
Thanks for all your help - appreciated! I think that's what I must have done.
