### ISSUE TITLE
"No path to the binary executable of X-13 specified" (M1 Mac)

### ISSUE THREAD

**Issue by elbersb** [christophsax/seasonal#267]
I may be missing something obvious, but on my M1 mac, I can only get `seasonal` to work when I explicitly set the path:

``` r
library("seasonal")
m <- seas(AirPassengers)
#> No path to the binary executable of X-13 specified.
#> 
#> You can set 'X13_PATH' manually if you intend to use your own
#> binaries. See ?seasonal for details.
#> Error in checkX13(fail = TRUE, fullcheck = FALSE, htmlcheck = FALSE): Process terminated
Sys.setenv(X13_PATH = x13binary::x13path())
m <- seas(AirPassengers)
```
<sup>Created on 2021-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I haven't looked too deeply into the problem, but [here](https://github.com/christophsax/seasonal/blob/main/R/startup.R#L4) it seems that the `.onLoad()` function returns early (because of M1) and the environment variable can never be set. When I call `seas()`, the package then calls `checkX13()`, which fails because the path is not set.

**Comment by christophsax** [comment]
M1 users @krlmlr or @elbersb,

could you please try again with the latest to see if it works?

```r
remotes::install_github("christophsax/seasonal")
seasonal::seas(AirPassengers)
```

Thanks Kirill, for the nice fix!

**Comment by elbersb** [comment]
Thanks, that works for me.

**Comment by christophsax** [comment]
Thanks, Benjamin, will upload to CRAN now.
