### ISSUE TITLE
Error : X-13 run failed

### ISSUE THREAD

**Issue by dblueeye** [christophsax/seasonal#275]
Thanks in advance!

> library(x13binary)
> checkX13()
seasonal is using the X-13 binaries provided by x13binary
X-13 installation test:
  - X13_PATH correctly specified
  - binary executable file found

Error : X-13 command line test run failed. To debug, try running the binary file directly in the terminal. Try using it with Testairline.spc which is part of the program package by the Census Office.

Error : seasonal test run failed, with the message:
Error : X-13 run failed

Errors:
- -I, -O, -M, -D, -C, -S, -N, -V, -R, -Q, -X, -T.

Error details:
  - X13_PATH:         C:/Users/Yen Ting Lin/Documents/R/win-library/4.1/x13binary/bin
  - Full binary path: "C:/Users/Yen Ting Lin/Documents/R/win-library/4.1/x13binary/bin/x13ashtml.exe"
  - Platform:         x86_64-w64-mingw32
  - R-Version:        R version 4.1.1 (2021-08-10)
  - seasonal-Version: 1.8.2

> session_info()
- Session info --------------------------------------------------------
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Denver              
 date     2021-10-04                  

- Packages ------------------------------------------------------------
 package     * version  date       lib source        
 cli           3.0.1    2021-07-17 [1] CRAN (R 4.1.1)
 seasonal    * 1.8.2    2021-03-29 [1] CRAN (R 4.1.1)
 sessioninfo * 1.1.1    2018-11-05 [1] CRAN (R 4.1.1)
 withr         2.4.2    2021-04-18 [1] CRAN (R 4.1.1)
 x13binary   * 1.1.39-3 2021-03-29 [1] CRAN (R 4.1.1)

[1] C:/Users/Yen Ting Lin/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.1/library

**Comment by dblueeye** [comment]
On another computer, different symptom but still can't run. 

> library(x13binary)
> library(seasonal)
> checkx13()
Error in checkx13() : could not find function "checkx13"
> checkX13()
seasonal is using the X-13 binaries provided by x13binary
X-13 installation test:
  - X13_PATH correctly specified
  - binary executable file found

Error : X-13 command line test run failed. To debug, try running the binary file directly in the terminal. Try using it with Testairline.spc which is part of the program package by the Census Office.

Error : seasonal test run failed, with the message:
Error in x13_import(iofile, x = list[["x"]], na.action = na.action, out = out) : 
  no output has been generated


Error details:
  - X13_PATH:         C:/Users/XXX/Documents/R/win-library/4.1/x13binary/bin
  - Full binary path: "C:/Users/XXX/Documents/R/win-library/4.1/x13binary/bin/x13ashtml.exe"
  - Platform:         x86_64-w64-mingw32
  - R-Version:        R version 4.1.1 (2021-08-10)
  - seasonal-Version: 1.8.4

> library(sessioninfo)
> session_info()
- Session info -------------------------------------
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Denver              
 date     2021-10-05                  

- Packages -----------------------------------------
 package     * version  date       lib source        
 cli           3.0.1    2021-07-17 [2] CRAN (R 4.1.1)
 colorspace    2.0-2    2021-06-24 [2] CRAN (R 4.1.1)
 crayon        1.4.1    2021-02-08 [2] CRAN (R 4.1.1)
 dplyr         1.0.7    2021-06-18 [2] CRAN (R 4.1.1)
 ellipsis      0.3.2    2021-04-29 [2] CRAN (R 4.1.1)
 fansi         0.5.0    2021-05-25 [2] CRAN (R 4.1.1)
 generics      0.1.0    2020-10-31 [2] CRAN (R 4.1.1)
 ggplot2       3.3.5    2021-06-25 [2] CRAN (R 4.1.1)
 glue          1.4.2    2020-08-27 [2] CRAN (R 4.1.1)
 gtable        0.3.0    2019-03-25 [2] CRAN (R 4.1.1)
 lifecycle     1.0.1    2021-09-24 [2] CRAN (R 4.1.1)
 magrittr      2.0.1    2020-11-17 [2] CRAN (R 4.1.1)
 munsell       0.5.0    2018-06-12 [2] CRAN (R 4.1.1)
 pillar        1.6.3    2021-09-26 [2] CRAN (R 4.1.1)
 pkgconfig     2.0.3    2019-09-22 [2] CRAN (R 4.1.1)
 purrr         0.3.4    2020-04-17 [2] CRAN (R 4.1.1)
 R6            2.5.1    2021-08-19 [2] CRAN (R 4.1.1)
 rlang         0.4.11   2021-04-30 [2] CRAN (R 4.1.1)
 scales        1.1.1    2020-05-11 [2] CRAN (R 4.1.1)
 seasonal    * 1.8.4    2021-09-18 [1] CRAN (R 4.1.1)
 sessioninfo * 1.1.1    2018-11-05 [1] CRAN (R 4.1.1)
 tibble        3.1.5    2021-09-30 [2] CRAN (R 4.1.1)
 tidyselect    1.1.1    2021-04-30 [2] CRAN (R 4.1.1)
 utf8          1.2.2    2021-07-24 [2] CRAN (R 4.1.1)
 vctrs         0.3.8    2021-04-29 [2] CRAN (R 4.1.1)
 withr         2.4.2    2021-04-18 [2] CRAN (R 4.1.1)
 x13binary   * 1.1.57-2 2021-08-12 [1] CRAN (R 4.1.1)

[1] C:/Users/XXX/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.1/library

**Comment by christophsax** [comment]
Weird. Haven't seen such problems, but will have a look on a Win machine asap.

**Comment by christophsax** [comment]
It seems you cannot run binaries from your user library. Perhaps you can try to install seasonal into `C:/Program Files/R/R-4.1.1/library`? 

Remove existing installation: `remove.packages("seasonal")`.
Remove the user libary (temporarily) from your libPaths: `.libPaths("C:/Program Files/R/R-4.1.1/library")`. And install again: `install.packages("seasonal")`.

To verify, `system.file(package = "seasonal")` should point to `C:/Program Files/R/R-4.1.1/library`, not to the user library.

**Comment by christophsax** [comment]
> Weird. Haven't seen such problems, but will have a look on a Win machine asap.

It's not weird. Seasonal (like many other packages) wants to run binaries in the library folder.
