### ISSUE TITLE
Problems when running seasonal in multiple threads using mclapply

### ISSUE THREAD

**Issue by jonlachmann** [christophsax/seasonal#276]
Hi!

I have a use case where I need to run seasonal inside multiple threads (in my case I want to run 12 threads in parallel). I do this using mclapply, but I get very inconsistent results. When running a simple example (below) sequentially, I get no errors. When I instead run the exact same thing in parallel, I get an assortment of errors, some of which are present below.

For the sake of being able to demonstrate the error I wrote this small bit of code. The version of seasonal I have tried this with is 1.8.3 and 1.8.4. The x13binary is version 1.1.57.2. I have used R version 4.1.2 and 3.6.3, on both OSX 12.2 and Ubuntu 18.04.

Please let me know if you need any further information on how to reproduce the problem.

```
# Load library
library(seasonal)
packageVersion("seasonal") # 1.8.3 and 1.8.4
packageVersion("x13binary") # 1.1.57.2

# Create some random data
set.seed(345)
data <- ts(1:100 + rnorm(100) + 1:12, start=c(2015, 01), frequency = 12)

# Run parallel
seas_runs_par <- mclapply(1:12, function(x) seas(data), mc.cores=12)

# Run sequentially
seas_runs <- vector("list", 12)
for (i in 1:12) {
  seas_runs[[i]] <- seas(data)
}

# Check for errors
sum(sapply(seas_runs, function (x) class(x)[1] == "try-error")) # 0
sum(sapply(seas_runs_par, function (x) class(x)[1] == "try-error")) # 9
```

Some errors that I get in the parallel run are
```
[1] "Error : X-13 run failed\n\nErrors:\n- Unable to open regression and ARMA parameter estimates, /tmp/RtmpHnN3Wq/x13406c29ffaaa1/iofile.est.\n\n"
attr(,"condition")
<simpleError: X-13 run failed

Errors:
- Unable to open regression and ARMA parameter estimates, /tmp/RtmpHnN3Wq/x13406c29ffaaa1/iofile.est.
>
```

and

```
[1] "Error in file(con, \"r\") : cannot open the connection\n"
attr(,"condition")
<simpleError in file(con, "r"): cannot open the connection>
```

**Comment by christophsax** [comment]
Sorry for the slow response!

This seems to be a problem of forking parallelization. `tempfile()`, for some reason, points to the same location, and each adjustment now works on the same directory:


``` r
library(parallel)
unlist(mclapply(1:4, function(x) tempfile(), mc.cores=4))
#> [1] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8d837af44a6"
#> [2] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8d937af44a6"
#> [3] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8da37af44a6"
#> [4] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8db37af44a6"
```


It's easy to circumvent by using cluster parallization. E.g.,

``` r
library(parallel)
cl <- makeCluster(4)
unlist(parLapply(cl, 1:4, function(x) tempfile()))
#> [1] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//Rtmpxp1Vsk/filed9324fddab16"
#> [2] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpZUpW65/filed93129954888"
#> [3] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//Rtmp5vhy2c/filed9335fc4fdc1"
#> [4] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpZMpD2h/filed934aba6a5e"
```


Applied to your problem, this will work:


``` r
library(parallel)
data <- ts(1:100 + rnorm(100) + 1:12, start=c(2015, 01), frequency = 12)
#> Warning in 1:100 + rnorm(100) + 1:12: longer object length is not a multiple of
#> shorter object length
cl <- makeCluster(4)
clusterExport(cl, "data")
ans <- parLapply(cl, setNames(1:4, paste0("s", 1:4)), function(x) seasonal::seas(data))
head(do.call(cbind, lapply(ans, seasonal::final)))
#>             s1        s2        s3        s4
#> [1,]  5.968123  5.968123  5.968123  5.968123
#> [2,]  8.995635  8.995635  8.995635  8.995635
#> [3,]  9.084451  9.084451  9.084451  9.084451
#> [4,] 10.665621 10.665621 10.665621 10.665621
#> [5,] 11.066765 11.066765 11.066765 11.066765
#> [6,] 12.093065 12.093065 12.093065 12.093065
```


The furrr package makes these things a little easier:

``` r
library(furrr)
plan(multisession, workers = 4)
ans <- future_map(setNames(1:4, paste0("s", 1:4)), function(x) seasonal::seas(data))
```


In principle, it would be possible to tell seasonal to work in something more unique than `tempfile()`, but I am not sure if it is worth the pain. After all, forking does not work under Windows, and in RStudio, so many users have to use cluster parallelization anyway. Also, any other package that operates on a `tempfile()` will have the same problem. Would like to know more first how this problem is handled in general.

**Comment by jonlachmann** [comment]
> Sorry for the slow response!
> 
> This seems to be a problem of forking parallelization. `tempfile()`, for some reason, points to the same location, and each adjustment now works on the same directory:
> 
> ```r
> library(parallel)
> unlist(mclapply(1:4, function(x) tempfile(), mc.cores=4))
> #> [1] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8d837af44a6"
> #> [2] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8d937af44a6"
> #> [3] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8da37af44a6"
> #> [4] "/var/folders/hp/j2kyw2dj23b0mhpzq0qh7vbh0000gn/T//RtmpChLA7d/filed8db37af44a6"
> ```
Hi!

Thank you for looking into this, actually I think that you came to the same conclusion as I did, which turned out to be wrong. The tempfiles are _not_ the same, just really similarly named. Look at the file names, they are called "filed8d", but then have different letters.

I also checked by running my example from the first post, getting errors pointing to files that could not be found in
```
/var/folders/j7/bj_2bbsn5fd8r9_7f07tlhp00000gn/T//RtmpNhQ1Uw/x1380e652388438/iofile.s10.
/var/folders/j7/bj_2bbsn5fd8r9_7f07tlhp00000gn/T//RtmpNhQ1Uw/x1380e952388438/iofile.s10.
```
where we can see that the folders are all called "x1380e" but have a differing next digit.

It is however interesting that most errors I am getting point to problems with finding the files that x13 uses. About the case for parLapply vs. seasonal. It is a valid fix indeed, but mclapply and forking in general has _much_ less overhead than parLapply. If (as in my case) you need to run very many instances of seasonal it quickly becomes infeasible in a given timeframe.

Please let me know if you need me to dig around further, or if I can be of any assistance to help work towards a solution. I would be happy to provide a PR once we have a better hunch about what the problem is.

Best regards Jon

**Comment by christophsax** [comment]
You are right, they are different indeed. So it not `tempfile()` but something else, which we haven't seen yet. 

Great if you can help me with that.

**Comment by christophsax** [comment]
Added a test and merged. Thanks for the help!
