### ISSUE TITLE
Application unexpectedly exited

### ISSUE THREAD

**Issue by dsn1978** [christophsax/seasonal#283]
Hi, I have used seasonal.website for several years. The last several times I have tried to use it, I get this error message: "Application unexpectedly exited. Diagnostic info has been dumped to the Javascript console." I get this error in Chrome and Edge.

I am no programmer. I just know the basics to do the s.a. I need. 

Could you help please?

Thanks
dsn1978

**Comment by christophsax** [comment]
Thanks for the report. I played around a little and it seemed fine to me. Can you try again? If it persists, I will reboot the server.

**Comment by dsn1978** [comment]
Good day
Thank you, I still get the same error message, on Edge and on Chrome. Could it be something wrong with my computer settings? I am not an IT guy/programmer, so I rally don't know.
Thanks again for the help.David
    On Sunday, 17 April 2022, 01:01:33 GMT+12, Christoph Sax ***@***.***> wrote:  
 
 


Thanks for the report. I played around a little and it seemed fine to me. Can you try again? If it persists, I will reboot the server.

**Comment by christophsax** [comment]
Rebooted now. If it persists, can you tell me in more details what you are doing. E.g.: 1) start the website, 2) with basic AirPassengers, select some options, 3) upload series, 4) as soon as I click this, it crashes.

Chrome and Edge should be fine, it's not your local settings.

**Comment by dsn1978** [comment]
Thanks again for reaching out. Here is a snip of the message I get. I get it as soon as I have uploaded a file in CSV or XLSX. All the other functions seem to work for the existing dummy data you have in there on Air Passengers.
Thanks againDavid



    On Monday, 18 April 2022, 14:27:01 GMT+12, Christoph Sax ***@***.***> wrote:  
 
 


Rebooted now. If it persists, can you tell me in more details what you are doing. E.g.: 1) start the website, 2) with basic AirPassengers, select some options, 3) upload series, 4) as soon as I click this, it crashes.

Chrome and Edge should be fine, it's not your local settings.
