### ISSUE TITLE
I'm having problems with 'x13binary' and 'seasonal' packages

### ISSUE THREAD

**Issue by AngeloLopezPadilla** [christophsax/seasonal#291]
Install the packages and it gives me the following errors. Is there a solution?

**Comment by eddelbuettel** [comment]
Some quick ones:

- If possible, do NOT post images.  Copy and paste textual error messages
- If possible, include _full_ details of _what command you executed_ and on which equipment

Here the error is quite clear and in the first line "binaries do not work here".  Maybe you use an M1 mac -- we do not know as you did not say.  Or maybe something else.  Somehow you ended up with the wrong binary -- but you did not show us how.  

Which, sadly, makes it near-impossible for us to help you.

**Comment by eddelbuettel** [comment]
Right on -- glad you have it working now. Maybe it was a windows 32bit vs 64bit setup issue.  Hard to tell.
