### ISSUE TITLE
Parsing bug in import.spc

### ISSUE THREAD

**Issue by chuckcoleman-work** [christophsax/seasonal#292]
I have an .spc file with the command:

file='M:/Manufacturing, Investment and Construction Programs/CSSMB/SOC/Work for SK/Resimprov/lag0.dat'

When I run lag0.x13.spc <- import.spc("lag0_frcst202002_R.spc"), I get

>lag0.x13.spc$x
x <- import.ts("M:/Manufacturing,)\nx <- import.ts(Investment)\nx <- import.ts(and)\nx <- import.ts(Construction)\nx <- import.ts(Programs/CSSMB/SOC/Work)\nx <- import.ts(for)\nx <- import.ts(SK/Resimprov/lag0.dat")

Replacing the single quotes with double quotes fixes the problem.  Nonetheless, this could be a problem for some.

**Comment by christophsax** [comment]
We tweaked the spc import quite a bit in the latest release, so this may be resolved.
