### ISSUE TITLE
X-13 ARIMA SEATS seasonal adjustment

### ISSUE THREAD

**Issue by totainsh** [christophsax/seasonal#299]
GREAT package! One seeming bug I've encountered: the default mode is to use SEATS seasonal adjustment. When I added a single xreg variable:

 aj <- seas(x = s, xreg = regs)

I immediately get an error:

Error: X-13 run failed

Errors:
- forecasts end date, 2025.Nov, must end on or before user-defined
  regression variables end date, 2022.Dec.

**Comment by christophsax** [comment]
Could you please provide a reproducible example? Thanks. See [here](https://github.com/christophsax/seasonal/wiki/Creating-a-Reproducible-Example).

**Comment by christophsax** [comment]
Please reopen and provide a reproducible example if this is still something.
