### ISSUE TITLE
Too many observations in file

### ISSUE THREAD

**Issue by pereriksson** [christophsax/seasonal#309]
Hi!

I have a data frame with 3180 observations that I have converted into a ts object.

```
data.ts <- ts(data$temp, frequency = 12, start = c(1756, 1))
```

When runnin `seas(data.ts)` command I get the following error:

`ERROR:   Problem reading /var/folders/t1/ntr9jsz9137cktgy_r_pfr8m0000gn/T//Rtmp56d4hz/x1363615487e913/iofile.dta. Too many observations in file.`

The iofile.dta file is 36K and it has my 3180 observations.
```
% wc -l iofile.dta 
    3180 iofile.dta
```

Any idea what the issue could be? I am on Apple Silicon.

**Comment by a-s-russo** [comment]
According to Table 2.2 in section 2.8 of the [USCB's reference manual for X-13ARIMA-SEATS,](https://www2.census.gov/software/x-13arima-seats/x-13-data/documentation/docx13as.pdf) the maximum series length is 780 observations. The same section notes that these limits can possibly be changed, but I'm not sure how they can be changed via the `seasonal` package.

**Comment by pereriksson** [comment]
@a-s-russo thanks!
