### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by BriBriOs** [christophsax/seasonal#311]
I've been trying to install the seasonal package with the command install.packages("seasonal")  and get the following error:

  * installing *source* package ‘x13binary’ ...
  ** package ‘x13binary’ successfully unpacked and MD5 sums checked
  ** using staged installation
  Error in download.file("https://github.com/x13org/x13prebuilt/raw/master/v1.1.57/linux/64/x13ashtml",  : 
    cannot open URL 'https://github.com/x13org/x13prebuilt/raw/master/v1.1.57/linux/64/x13ashtml'
  In addition: Warning message:
  In download.file("https://github.com/x13org/x13prebuilt/raw/master/v1.1.57/linux/64/x13ashtml",  :
    URL 'https://raw.githubusercontent.com/x13org/x13prebuilt/master/v1.1.57/linux/64/x13ashtml': status was 'SSL peer certificate or SSH remote key was not OK'
  Execution halted
  ERROR: configuration failed for package ‘x13binary’
  * removing ‘/home/bri/R/x86_64-pc-linux-gnu-library/4.1/x13binary’
  Warning in install.packages :
    installation of package ‘x13binary’ had non-zero exit status
  ERROR: dependency ‘x13binary’ is not available for package ‘seasonal’
  * removing ‘/home/bri/R/x86_64-pc-linux-gnu-library/4.1/seasonal’
  Warning in install.packages :
    installation of package ‘seasonal’ had non-zero exit status

I believe the problem is during the installation of x13binary, but I haven't found a way of fixing this. It says "can't access URL..." so I typed it into the browser and got a file "x13ashtml" , but I don't know what to do with it....I tried uninstalling R. I am able to install other packages. I would appreciate any help, thanks.

**Comment by eddelbuettel** [comment]
If that happened just today it may be due to some _temporary_ issues with curl library.  Are you by chance on Ubuntu?

Maybe do an `apt update; apt upgrade` to get a new `curl` library.  It works here (and I just did my daily update a little while ago):

```
> install.packages(c("seasonal", "x13binary"))
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/seasonal_1.9.0.tar.gz'
Content type 'application/x-gzip' length 2180205 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://cran.r-project.org/src/contrib/x13binary_1.1.57-3.tar.gz'
Content type 'application/x-gzip' length 10833 bytes (10 KB)
==================================================
downloaded 10 KB

begin installing package ‘x13binary’
* installing *source* package ‘x13binary’ ...
** package ‘x13binary’ successfully unpacked and MD5 sums checked
** using staged installation
*** downloaded Linux binary
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (x13binary)
begin installing package ‘seasonal’
* installing *source* package ‘seasonal’ ...
** package ‘seasonal’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (seasonal)

The downloaded source packages are in
	‘/tmp/Rtmpu59TiI/downloaded_packages’
> 
```

**Comment by eddelbuettel** [comment]
Let us know if it works for you too.

**Comment by BriBriOs** [comment]
Thank you for the quick response; It worked! Thanks a lot :)!. Yes I recently changed from Windows 7 to Ubuntu and have very little experience with it.

**Comment by eddelbuettel** [comment]
Perfect. And Ubuntu is pretty good: not only does it generally 'not break', if something inadvertent like this happens fixes are quick.

(Minor personal ad: if you ever grow tired of compiling CRAN packages or chasing dependencies, I built [r2u](https://eddelbuettel.github.io/r2u) that gets you _all_ of CRAN via `apt`.  If you are new to Unix/Linux it may be confusing now but is something you can always revisit.  It makes more complicated install steps a total breeze.)

**Comment by BriBriOs** [comment]
Thanks, I'll check it out :)!
