### ISSUE TITLE
Make error for inserting a level shift in most recent period more informative

### ISSUE THREAD

**Issue by a-s-russo** [christophsax/seasonal#312]
When a level shift is specified via the `regression.variables` and `regression.b` arguments to `seas()` for the most recent time period, X-13 will fail to run because a level shift correction cannot occur at the current end of a series. However, the error that `seas()` throws is not helpful in understanding this:

```
Error: X-13 run failed

Errors:
- Number of initial values is not the same as the number of regression variables.
- Number of initial values is not the same as the number of regression variables.

Notes:
- Correct input errors in the order they are detected since the first one or two may be responsible for the others
  (especially if there are errors in the SERIES or COMPOSITE spec).
```

The error message should be worded more informatively along the lines of 'Error: a level shift correction cannot be inserted in the most recent time period'.

Note that `seas()` should not silently remove the level shift correction, as the user may wish to insert an additive outlier correction instead rather than remove any form of correction. Hence this situation should be brought to the user's attention (via the above suggested error message) for manual handling.

**Comment by christophsax** [comment]
Sorry, for the delayed response. 

I guess seasonal just relies on how X-13 handles this. We don't intend to add messages for specific problems on top of what X-13 does.

**Comment by a-s-russo** [comment]
Thanks for your reply. That's understandable. For what it's worth, just noting that this might be a 'value-add' opportunity for your package over the original program.
