### ISSUE TITLE
When calling the seas function, an error occurs indicating that it cannot open the linkage. 

### ISSUE THREAD

**Issue by qizhengyan** [christophsax/seasonal#319]
```r
> setwd("C:/Users/11066/Desktop/q")
> library(seasonal)
> data = read.csv("qq.csv")
> pmi=ts(data,start=c(2019,1),end=c(2023,12),frequency = 12)
> cny.ts <- genhol(cny, start = -15, end = 15, center = "calendar")
> m1 <- seas(x = pmi, xreg = cny.ts, regression.usertype = "holiday",x11 = "")
```
When I run the code above, an error occurs. The data import part works fine, but there is an error when running the seas function. The error message is:

```r
error In file(con, "r") :cannot open file 'C:\Users\11066\AppData\Local\Temp\RtmpWWz6vg\x1353411f619c1/ser1.est': No such file or directory
```

I tried reinstalling the package, but the same error still occurs repeatedly.

**Comment by christophsax** [comment]
@qizhengyan, could you resolve it? If not, I would need a [reproducible example](https://github.com/christophsax/seasonal/wiki/Creating-a-Reproducible-Example). E.g., you should use `dput()` on the `pmi` object and integrate the result in your example.

**Comment by christophsax** [comment]
I am closing this, feel free to reopen.
