### ISSUE TITLE
I need to do a multiplicative seasonal adjustment, but also using the X11 method instead of the default X13, while also specifying the ARIMA model to a (0,1,1) (0,1,1)

### ISSUE THREAD

**Issue by CamiSL2024** [christophsax/seasonal#330]
#packages to reproduce the problem
library(seasonal)

#data to reproduce the problem, "y" its the variable I want to seasonally adjust
y<-c(52841, 65274, 68947, 68117, 79521, 80172, 72684, 76700, 76192, 74416, 78631, 90307, 64452, 73733, 79562, 72748, 75754, 55358, 46637, 52224, 42628, 37207, 33095, 48418, 30038, 30404, 33708, 28469, 27947, 36501, 39255, 38021, 26876, 27204, 22900, 31151, 25727, 27191, 18922, 7512, 20033, 23773, 22475, 28346, 35065, 33320, 31431, 38994, 27303, 26676, 32359, 29876, 28025, 28187, 24369, 26069, 25700, 25291, 27811, 32723, 20147, 25432, 33827, 30861, 33730, 37236, 29432, 29171, 34605, 33087, 35212, 33517, 22112, 30125, 38087, 33795, 38604, 44138, 30928, 30294, 43282, 40788, 29715, 25072, 15942, 33234, 30176, 22450, 27851, 32333)

#I transformed the variable "y" in a time series
y_ts <- ts(y, start = c(2017, 1), frequency = 12)

#the problem
#I need to do a multiplicative seasonal adjustment for "y", but also using the X11 method instead of the default X13, while also specifying the ARIMA model to a (0,1,1) (0,1,1)
#Here is my code for doing the adjustment for "y" with the x11 method and the arima model (0 11) (0 1 1) but i don´t know how to specify that the adjustment needs to be multiplicative

m <- seas(y_ts, x11="")
y_sa <- update(m,arima.model = "(0 1 1) (0 1 1)")
y_adj <- final(y_sa)

#I appreciate any help on this matter! Thank you

**Comment by CamiSL2024** [comment]
#packages to reproduce the problem
library(seasonal)

#data to reproduce the problem, "y" its the variable I want to seasonally adjust
y<-c(52841, 65274, 68947, 68117, 79521, 80172, 72684, 76700, 76192, 74416, 78631, 90307, 64452, 73733, 79562, 72748, 75754, 55358, 46637, 52224, 42628, 37207, 33095, 48418, 30038, 30404, 33708, 28469, 27947, 36501, 39255, 38021, 26876, 27204, 22900, 31151, 25727, 27191, 18922, 7512, 20033, 23773, 22475, 28346, 35065, 33320, 31431, 38994, 27303, 26676, 32359, 29876, 28025, 28187, 24369, 26069, 25700, 25291, 27811, 32723, 20147, 25432, 33827, 30861, 33730, 37236, 29432, 29171, 34605, 33087, 35212, 33517, 22112, 30125, 38087, 33795, 38604, 44138, 30928, 30294, 43282, 40788, 29715, 25072, 15942, 33234, 30176, 22450, 27851, 32333)

#I transformed the variable "y" in a time series
y_ts <- ts(y, start = c(2017, 1), frequency = 12)

#the problem
#I need to do a multiplicative seasonal adjustment for "y", but also using the X11 method instead of the default X13, while also specifying the ARIMA model to a (0,1,1) (0,1,1)
#Here is my code for doing the adjustment for "y" with the x11 method and the arima model (0 11) (0 1 1) but i don´t know how to specify that the adjustment needs to be multiplicative

m <- seas(y_ts, x11="")
y_sa <- update(m,arima.model = "(0 1 1) (0 1 1)")
y_adj <- final(y_sa)

#I appreciate any help on this matter! Thank you

**Comment by christophsax** [comment]
By default, seasonal uses `transform.function = "auto"`, which automatically decides between multiplicative and additive adjustment. If you want to enforce a multiplicative adjustment, use `transform.function = "log"`. In the `monthplot()`, you can see that your seasonal component is now a factor around 1.

``` r
library(seasonal)

y <- c(52841, 65274, 68947, 68117, 79521, 80172, 72684, 76700, 76192, 74416, 78631, 90307, 64452, 73733, 79562, 72748, 75754, 55358, 46637, 52224, 42628, 37207, 33095, 48418, 30038, 30404, 33708, 28469, 27947, 36501, 39255, 38021, 26876, 27204, 22900, 31151, 25727, 27191, 18922, 7512, 20033, 23773, 22475, 28346, 35065, 33320, 31431, 38994, 27303, 26676, 32359, 29876, 28025, 28187, 24369, 26069, 25700, 25291, 27811, 32723, 20147, 25432, 33827, 30861, 33730, 37236, 29432, 29171, 34605, 33087, 35212, 33517, 22112, 30125, 38087, 33795, 38604, 44138, 30928, 30294, 43282, 40788, 29715, 25072, 15942, 33234, 30176, 22450, 27851, 32333)

y_ts <- ts(y, start = c(2017, 1), frequency = 12)

m <- seas(y_ts, x11="", arima.model = "(0 1 1) (0 1 1)", transform.function = "log")

summary(m)
#> 
#> Call:
#> seas(x = y_ts, transform.function = "log", x11 = "", arima.model = "(0 1 1) (0 1 1)")
#> 
#> Coefficients:
#>                   Estimate Std. Error z value Pr(>|z|)    
#> LS2020.Mar        -0.51352    0.12280  -4.182 2.89e-05 ***
#> AO2020.Apr        -0.87588    0.07772 -11.270  < 2e-16 ***
#> AO2024.Feb         0.38718    0.09031   4.287 1.81e-05 ***
#> MA-Nonseasonal-01 -0.24721    0.10840  -2.281 0.022573 *  
#> MA-Seasonal-12     0.42319    0.12326   3.433 0.000596 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> X11 adj.  ARIMA: (0 1 1) (0 1 1)  Obs.: 90  Transform: log
#> AICc:  1535, BIC:  1548  QS (no seasonality in final):    0  
#> Box-Ljung (no autocorr.): 29.07   Shapiro (normality): 0.9714 *

monthplot(m)
```

![](https://i.imgur.com/3NMWHAN.png)

<sup>Created on 2024-10-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
