### ISSUE TITLE
Using modelspan: historical values dont match spanned values.

### ISSUE THREAD

**Issue by mwalkup55** [christophsax/seasonal#80]
I do not understand why the values before 12/1979 are different under these calls.  They both should be estimating data only through 11/1979 and applying the coefficients to 12/1979 in the first case.  Is this a bug, or am I specifying the parameters incorrectly.  Thanks!

    library(seasonal)
    data<-fdeaths
    model1<-seas(x=data,series.modelspan=",1979.11")
    final(model1)

    ##           Jan      Feb      Mar      Apr      May      Jun      Jul
    ## 1974 605.0662 545.9147 593.3950 604.1508 597.7473 555.6615 590.0947
    ## 1975 560.5651 583.8194 563.9643 597.1732 541.7031 584.8572 563.8516
    ## 1976 521.3012 844.2007 630.3859 485.4044 517.7286 549.8407 507.5933
    ## 1977 582.5976 492.0419 480.8574 587.0140 562.5317 510.0401 551.3516
    ## 1978 533.1267 612.3131 538.7238 507.4041 581.8252 571.2519 572.9872
    ## 1979 545.2185 558.5225 538.7767 559.8161 527.8549 551.7957 534.1183
    ##           Aug      Sep      Oct      Nov      Dec
    ## 1974 582.6049 590.5187 670.9974 612.9328 535.8005
    ## 1975 617.0855 517.7339 524.9388 576.4575 601.4356
    ## 1976 498.8215 528.1686 555.1827 596.4082 596.1657
    ## 1977 521.7353 557.4495 493.2286 470.6314 515.5515
    ## 1978 539.7098 554.2983 550.3738 495.3388 565.4749
    ## 1979 559.8585 562.1675 524.2813 562.1744 489.3388
    
    model2<-seas(x=data,series.span=",1979.11")
    final(model2)
    ##           Jan      Feb      Mar      Apr      May      Jun      Jul
    ## 1974 605.5057 546.3727 593.9585 604.7898 598.4428 556.3657 590.9025
    ## 1975 561.0492 584.3838 564.5678 597.8738 542.3945 585.6640 564.6875
    ## 1976 521.8459 845.1881 631.2033 486.0965 518.5348 550.7703 508.5203
    ## 1977 583.3691 492.7840 481.6734 588.1241 563.7074 511.2101 552.7317
    ## 1978 534.0783 613.5887 540.0118 508.7782 583.5907 573.1773 575.1162
    ## 1979 546.6161 560.2349 540.7082 562.1229 530.3216 554.6882 537.2311
    ##           Aug      Sep      Oct      Nov      Dec
    ## 1974 583.4602 591.4429 672.1112 614.0070 532.7590
    ## 1975 618.0640 518.6081 525.8793 577.5497 596.7612
    ## 1976 499.8013 529.2799 556.4298 597.8340 588.7758
    ## 1977 523.1529 559.0863 494.7873 472.2266 504.7826
    ## 1978 541.9067 556.7565 553.0202 497.9103 545.3116
    ## 1979 563.4587 566.1309 528.3112 566.8628

**Comment by mwalkup55** [comment]
Just to clarify, I want to find the seasonally adjusted value for 12/1979 using the coefficients calculated 1/1974-11/1979.  I would expect that the modelspan parameter would force x13 to only use dates through 11/1979 to calculate coefficients and then simply apply it to the extra datapoint, but instead it alters the 1/1974-11/1979 data after the 12/1979 data is included.

**Comment by christophsax** [comment]
It's not a bug. `series.modelspan` modifies the sample used for the estimation of the regARIMA model, which is indeed the same in the two models, as you can verify with `summary`.

The estimation of the seasonal factor is still affected by the new data point, both with SEATS and X11, so the whole series changes. I can see why you want to have a revision free series but don't know how to do this in X13. If you figure it out, please let me know, I would be interested in this as well.
