### ISSUE TITLE
Error in seas(ts) : Adding LS2002.Sep exceeds the number of regression effects allowed in the model (80).

### ISSUE THREAD

**Issue by mikeasilva** [christophsax/seasonal#91]
I have a question: When making an X-13ARIMA-SEATS seasonal adjustment I am getting an error that adding a variable exceeds the number of regression effects allowed in the model (80).  Is it possible to increase this ceiling? Thanks in advance!

**Comment by christophsax** [comment]
I guess so, but this is an X-13 issue. Have a look at section 2.8 in the X-13 manual (http://www.census.gov/ts/x13as/docX13AS.pdf). However, you need to recompile the fortran code, and I cannot help you with that. But does it really make sense to have more than 80 regressors? Surely, the estimation of the coefficients will be terrible...

**Comment by mbannert** [comment]
I guess @christophsax is right here. The US Census Bureau has a long history of dealing with X-13 and they don't set this limit for no reason. Could it be possible that R mistakenly interprets some continuos variable as a factor / categorical and thus you end up with too many regressor?

**Comment by mikeasilva** [comment]
Thank you @christophsax and @mbannert  for your comments.  I really don't want 80 regressors.  I have checked my data and it is all numeric.  I'll dig into the documentation.  Thanks again for your help.

**Comment by cestob** [comment]
have you tried setting outlier.types?
