### ISSUE TITLE
Instructions for Compiling X 13ARIMA SEATS from Source for OS X

### ISSUE THREAD

**Issue by letsgoexploring** [christophsax/seasonal#93]
First of all, thank you for this. I used it today and the process was quick and easy. 

Second, in instruction 2, you say to download **x13assrc_V1.1_B19**. In all subsequent instructions it appears you reference **x13ashtml_V1.1_B19** I followed the instructions using **x13assrc_V1.1_B19** and everything worked perfectly except that I obviously had to change the command in line 9 to `./x13as`.

It might be helpful to point out that people using x13 through the Statsmodels Python package need to go the **x13assrc_V1.1_B19** route because Statsmodels only looks for x12a and x13as.

Thanks again!

Brian

**Comment by christophsax** [comment]
Thanks, Brian. Updated as you suggested.
